import {esc,icon} from './src/ui.js';
import { html, render as mount } from 'lit';
import { live } from 'lit/directives/live.js';
(function (root) {
  'use strict';

  const G = root.Game;
  const ratingFrames = ['normal', 'blue', 'green', 'orange', 'red', 'purple', 'bronze', 'silver', 'gold', 'platinum', 'rainbow'];
  function setup(s, draft, offers, run) {
    return html`<main class="setup-screen"><header><span class="brand-mark">${icon('disc-3')}</span><div><h1>出勤模拟器</h1><p>2026 春季篇 · 第 ${run} 周目</p></div></header><form id="setup-form"><div class="setup-identity"><label>玩家姓名<input id="player-name" maxlength="16" value="${esc(draft.name)}" placeholder="神秘人"></label><label>舞萌 ID<input id="player-id" maxlength="16" value="${esc(draft.id)}" placeholder="Maimai"></label></div><fieldset><legend>选择职业</legend><div class="setup-jobs">${Object.entries(G.JOBS).map(([id, j]) => html`<label class="setup-choice"><input type="radio" name="career" value="${id}" ?checked=${draft.job === id}><span>${icon(j.icon)}<b>${j.name}</b><small>初始 ¥${j.money}</small><small>${j.detail}</small><small>${id === 'student' ? '按课表上课，节假日调休' : id === 'worker' ? '工作日 09:00–18:00 上班' : '时间自由，可接兼职'}</small></span></label>`)}</div></fieldset><fieldset><legend>惯用打法</legend><div class="setup-styles">${Object.entries(G.PLAY_STYLES).map(([id,p])=>html`<label class="setup-choice"><input type="radio" name="play-style" value=${id} ?checked=${(draft.playStyle||'outer')===id}><span>${icon(id==='outer'?'keyboard':'hand')}<b>${p.name}</b><small>${id==='outer'?'键盘力 +0.4 · 星星力 -0.4':'星星力 +0.4 · 键盘力 -0.4'}</small><small>影响初始底力，后续均可练习成长</small></span></label>`)}</div></fieldset><fieldset><legend>初始词条 · 三选一</legend><div class="talent-draw">${offers.map(id => {
      const t = G.TALENTS.find(t => t.id === id);
      return html`<label class="setup-choice"><input type="radio" name="talent" value="${id}" ?checked=${draft.talent === id}><span>${icon('sparkles')}<b>${t.name}</b><small>${t.description}</small></span></label>`;
    })}</div></fieldset><div class="setup-footer"><span>${icon('hand')}随身物品：棉线手套 · 100 耐久</span><button type="submit" class="primary-btn">${icon('arrow-right')}开始春季生活</button></div></form></main>`;
  }
  function player(s) {
    const tier = G.ratingTier(s.rating),
      condition = G.CONDITIONS[s.condition],
      rank = G.friendRank(s), course = Math.max(0, ...s.competition.courses),
      title = G.collectionItem(s.profile.title), color = ['Normal','Bronze','Silver','Gold','Rainbow'].includes(title?.color) ? title.color : 'Normal';
    return html`<section class="player-nameplate" aria-label="玩家名牌与状态"><div class="nameplate-top cabinet-nameplate" style="background-image:url('assets/plates/${encodeURIComponent(s.profile.plate)}.png')"><button class="player-avatar" data-action="avatar" title="自定义头像" aria-label="自定义头像">${s.profile.avatar || root.AVATARS?.[0]?.src ? html`<img src="${s.profile.avatar || root.AVATARS[0].src}" alt="玩家头像">` : icon('disc-3')}</button><div class="player-identity"><div class="cabinet-rating-row"><div class="mainland-rating tier-${tier}" aria-label="DX Rating ${s.rating}"><img src="assets/rating/wahlap/rating_base_${ratingFrames[tier - 1]}.png" alt="舞萌 DX 国服 Rating 框"><div class="mainland-rating-digits" aria-hidden="true">${String(s.rating).padStart(5, '0').split('').map(digit => html`<img src="assets/rating/diving-fish/UI_NUM_Drating_${digit}.png" alt="">`)}</div></div><img class="cabinet-class" src="assets/class_rank/${rank}.webp" alt="友人对战 ${G.FRIEND_RANKS[rank]}" title="友人对战 ${G.FRIEND_RANKS[rank]}"></div><div class="cabinet-name-row"><h2 title="${s.profile.id}">${esc(s.profile.id)}</h2><img class="cabinet-course" src="assets/course_rank/${course ? course+11 : 0}.webp" alt="${course ? G.COURSE_NAMES[course-1] : '初学者'}" title="${course ? G.COURSE_NAMES[course-1] : '初学者'}"></div><span class="player-title" style="background-image:url('assets/cabinet/UI_CMN_Shougou_${color}.png')" title="${title?.name || '新人出道'}">${esc(title?.name || '新人出道')}</span></div></div><div class="player-life-line"><span>${esc(s.profile.name)} · ${G.JOBS[s.job].name}</span><span>目标 16,000</span></div><div class="player-status"><div class="money"><small>${icon('wallet')}钱包</small><b>¥${s.money}</b><span>今日基础 -¥${G.dailyExpense(s)}</span></div><div><small>${icon('heart')}心情</small><b>${Math.round(s.mood)}<em>/100</em></b><span class="condition condition-${s.condition}">今日舞萌状态：${condition.name}</span></div><div><small>${icon('battery-medium')}体力</small><b>${Math.floor(s.stamina)}<em>/${s.maxStamina}</em></b><progress max="${s.maxStamina}" value="${s.stamina}"></progress></div><div><small>${icon('hand')}手套</small><b>${Math.floor(s.gloves.durability)}<em>耐久</em></b><span>${esc(s.gloves.name)}</span></div></div><div class="drowsiness-strip">${icon('moon')}<b>困意 ${Math.round(s.drowsiness)}/100</b><progress max="100" value=${s.drowsiness}></progress><span>${G.sleepPenalty(s)>0?`预期达成率 -${G.sleepPenalty(s).toFixed(2)}%`:'清醒'}</span></div><div class="skill-strip"><span>${icon('star')}星星 <b>${s.skills.star.toFixed(2)}</b></span><span>${icon('keyboard')}键盘 <b>${s.skills.key.toFixed(2)}</b></span><span>${icon('scan-eye')}读谱 <b>${s.skills.reading.toFixed(2)}</b></span><button class="text-btn" data-action="talents">${icon('sparkles')}词条 ${s.talents.length}</button></div></section>`;
  }
  function supplies(s) {
    return html`<div class="supply-strip"><span>${icon('battery-medium')}体力 ${Math.floor(s.stamina)}/${s.maxStamina}</span><span>${icon('cup-soda')}饮料 ${s.liquid} ml · ${s.bottles.length}/3 瓶</span><span>${icon('hand')}耐久 ${Math.floor(s.gloves.durability)}</span>${G.allNight(s)&&s.trip?html`<span>猫窝 ¥30/小时 · 已用 ${s.trip.denMinutes} 分钟 / 已付 ${s.trip.denHours} 小时</span>`:''}<span class="condition condition-${s.condition}">今日状态：${G.CONDITIONS[s.condition].name}</span></div><div class="drowsiness-strip">${icon('moon')}<b>困意 ${Math.round(s.drowsiness)}/100</b><progress max="100" value=${s.drowsiness}></progress><span>${G.sleepPenalty(s)>0?`预期达成率 -${G.sleepPenalty(s).toFixed(2)}%`:'清醒'}</span></div>${s.queueUntil<=s.clock?html`<p class="ready-label">轮到你上机了</p>`:''}<div class="supply-actions"><button class="secondary-btn" data-action="supplies">${icon('shopping-bag')}补给</button>${s.queueUntil > s.clock ? html`<button class="primary-btn" data-action="queue">${icon('clock-3')}等候 ${s.queueUntil - s.clock} 分钟</button>` : html`<button class="secondary-btn" data-action="queue">等待 15 分钟</button>`}${s.talents.includes('instinct') ? html`<label><input type="checkbox" id="instinct" ?checked=${s.instinct}>凭手感 · 底力 +0.3 / 体力消耗增加</label>` : ''}</div>${s.mode === 'pair' && s.partner !== null ? html`<div class="partner-line">${icon('users')}<div><b>${esc(s.npcs[s.partner].id)}</b><small>Rating ${s.npcs[s.partner].rating} · 眼熟度 ${s.npcs[s.partner].familiarity}/100</small></div><span>${s.friendship ? '“今天你多选一首！”' : '双方同时游玩'}</span><button class="secondary-btn" data-action="battle" aria-pressed=${s.competition.battle}>${icon('swords')}${s.competition.battle?'友人对战已开启':'友人对战'}</button></div>` : ''}`;
  }
  function mealStatus(s){return html`<div class="meal-status" aria-label="今日三餐">${G.MEAL_NAMES.map((name,i)=>html`<span class=${s.nutrition.meals[i]?'eaten':''}>${icon(s.nutrition.meals[i]?'circle-check':'utensils')}${name} · ${s.nutrition.meals[i]?'已吃':'未吃'}</span>`)}</div>`;}
  function bottles(s){return html`<div class="bottle-bag"><b>随身饮料 ${s.bottles.length}/3 瓶 · 剩余 ${s.liquid} ml</b>${s.bottles.length?s.bottles.map((b,i)=>html`<button class="secondary-btn" data-action="use-bottle" data-value=${i} aria-pressed=${i===0}>${G.DRINKS.find(d=>d.id===b.id).name} · ${b.ml} ml${i===0?' · 正在喝':''}</button>`):html`<span>暂未携带饮料</span>`}</div>`;}
  function drinkShop(s,action='pack-drink'){return html`${bottles(s)}<div class="option-grid">${G.drinkOptions(s).map(d=>{const reason=G.bottleReason(s,d.id);return html`<button class="option" data-action=${action} data-value=${d.id} ?disabled=${!!reason} title=${reason}>${icon(d.icon)}<div><b>${d.name}</b><small>${d.note}</small></div><span>¥${d.cost}<small>5 分钟</small></span></button>`;})}</div><p class="form-note">最多携带 3 瓶，大水最多 2 瓶。每首消耗 60 ml，喝完一瓶自动换下一瓶；仅当前饮料提供状态加成。</p>`;}
  function shop(s) {
    return html`<h3>手套</h3><div class="option-grid">${G.GLOVES.map(g => html`<button class="option" data-action="buy-gloves" data-value="${g.id}" ?disabled=${s.money < g.cost}>${icon('hand')}<div><b>${g.name}</b><small>耐久 ${g.durability}</small></div><span>¥${g.cost}</span></button>`)}</div>${s.phase === 'play' ? html`<h3>饮料补给</h3>${drinkShop(s,'refill')}` : ''}`;
  }
  function chat(s,guided=false) {
    return html`<div class="chat-window">${s.chat.map((m, index) => html`<article class="chat-message ${m.self ? 'self' : ''}"><div class="chat-avatar">${esc(m.id.slice(0, 1))}</div><div><small>${esc(m.id)} · ${G.time(m.time)}</small><p>${esc(m.self?m.text:m.text.replace(/SSS\+/g,'鸟加').replace(/SSS/g,'鸟'))}</p>${m.b50 ? html`<button class="chat-image-button" data-action="chat-image" data-value="${index}" aria-label="查看完整 B50 成绩图"><img class="chat-b50" data-b50-image="${index}" alt="群聊 B50 成绩图片"></button>` : ''}</div></article>`)}</div>${guided?'':html`<form id="chat-form" class="chat-compose"><input id="chat-message" maxlength="100" required aria-label="群聊消息" placeholder="在舞萌群发言"><button class="primary-btn" type="submit" title="发送消息" aria-label="发送消息">${icon('send')}</button></form><div class="chat-meta">发言 5 分钟 · 今日提升眼熟度 ${Math.min(s.chatDay === s.day ? s.chatCount : 0, 5)}/5 次 · @bot查看指令</div>`}`;
  }
  function plates(s, pool) {
    return html`<div class="plate-gallery">${G.plates(s, pool).map(p => html`<button class="plate-item ${s.profile.plate === p.id ? 'equipped' : ''}" data-action="equip-plate" data-value="${p.id}" ?disabled=${!p.unlocked}><div class="plate-preview" style="background-image:url('assets/plates/${encodeURIComponent(p.id)}.png')">${p.id === 'default' ? esc(p.name) : ''}</div><b>${p.name} ${s.profile.plate === p.id ? '· 已装备' : p.unlocked ? '· 可装备' : icon('lock-keyhole')}</b><small>${p.text}</small>${p.total ? html`<progress max="${p.total}" value="${p.done}"></progress><small>${p.done} / ${p.total} 张谱面</small>` : ''}</button>`)}</div>`;
  }
  function talents(s) {
    return html`<div class="talent-list">${G.TALENTS.filter(t => (!t.initial&&!t.hidden) || s.talents.includes(t.id)).map(t => html`<article class="${s.talents.includes(t.id) ? 'owned' : ''}"><span>${icon(s.talents.includes(t.id) ? 'sparkles' : 'lock-keyhole')}</span><div><b>${t.name}</b><p>${t.description}</p>${!s.talents.includes(t.id)&&Object.keys(G.talentGains(s,t.id)).length?html`<p class="talent-gain">当前可获：${G.talentGainText(G.talentGains(s,t.id))}</p>`:''}</div><small>${s.talents.includes(t.id) ? '已获得' : '未解锁'}</small></article>`)}</div>`;
  }
  function partnerChoices(s, pool) {
    if (s.mode !== 'pair' || !s.partnerSongs) return '';
    const names = ['BASIC', 'ADVANCED', 'EXPERT', 'MASTER', 'Re:MASTER'];
    return html`<div class="partner-choices"><h3>拼机伙伴的选曲 · 选择你的难度</h3>${s.partnerSongs.map((item, i) => {
      const charts = pool.filter(c => c.id === item.id),
        c = charts.find(c => c.index === item.index);
      return html`<label><img src="assets/covers/${item.id}.webp" alt="${esc(c.title)} 曲绘"><span><b>${esc(c.title)}</b><small>${c.type === 'DX' ? 'DX' : '标准'} · 拼机伙伴选择 ${names[item.index]} ${G.displayLevel(c)}</small></span><select data-partner-slot="${i}" aria-label="拼机伙伴第 ${i + 1} 首：我的难度">${charts.map(c => html`<option value="${c.index}" ?selected=${item.playerIndex === c.index}>${names[c.index]} ${G.displayLevel(c)}</option>`)}</select></label>`;
    })}</div>`;
  }
  function collections(s, pool, tab = 'achievement', query = '', page = 0, status = 'all') {
    const list = G.COLLECTIONS.filter(c => (tab === 'title' ? c.kind === 'title' : c.kind === 'plate' && (tab === 'achievement' ? ['achievement', 'default', 'song', 'other'].includes(c.category)&&!/覚醒|親密度/.test(c.description) : c.category === tab)) && (!query || `${c.name} ${c.description}`.toLowerCase().includes(query.toLowerCase()))).filter(c => status === 'all' || G.collectionProgress(s, c, pool).unlocked === (status === 'unlocked')),
      size = 18;
    return html`<div class="collection-summary"><button class="secondary-btn" data-action="ranks">${icon('medal')}段位与友人对战</button></div><div class="collection-tabs">${[['achievement', '名牌'], ['title', '称号'], ['stamp', '签到装饰'], ['region', '区域装饰']].map(([id, name]) => html`<button data-action="collection-tab" data-value="${id}" class="${tab === id ? 'selected' : ''}">${name}</button>`)}</div><div class="collection-tabs collection-status" aria-label="解锁状态">${[['all', '全部'], ['unlocked', '已解锁'], ['locked', '未解锁']].map(([id, name]) => html`<button data-action="collection-status" data-value="${id}" aria-pressed="${status === id}" class="${status === id ? 'selected' : ''}">${name}</button>`)}</div><label class="search-box collection-search">${icon('search')}<input id="collection-search" .value=${live(query)} placeholder="搜索名称 / 条件" aria-label="搜索收藏品"></label>${tab === 'stamp' ? html`<div class="collection-summary"><span>签到奖励：${esc(G.collectionItem(s.collection.stampTarget)?.name || '自动选择未完成奖励')}</span><span class="stamp-status" role="status">${icon('calendar-check')}${s.collection.lastStamp === s.day ? '今日已自动签到' : '首次上机后自动签到 · +2 进度'}</span></div>` : tab === 'title' ? html`<div class="collection-summary"><span>累计出勤距离：${s.collection.distanceKm.toFixed(1)} km · 去程与回程分别累计</span></div>` : tab === 'region' ? html`<div class="collection-summary"><span>当前区域：${esc(G.collectionItem(s.collection.regionTarget)?.region || '未选择')} · 每 PC 前进 1 / 共 10</span></div>` : ''}<div class="${tab === 'title' ? 'title-gallery' : 'plate-gallery'}">${list.slice(page * size, page * size + size).map(c => {
      const p = G.collectionProgress(s, c, pool),
        equipped = s.profile[c.kind === 'plate' ? 'plate' : 'title'] === c.id,
        active = s.collection[c.category === 'stamp' ? 'stampTarget' : 'regionTarget'] === c.id;
      return html`<article class="collection-item ${equipped ? 'equipped' : ''}">${c.kind === 'plate' ? html`<img class="collection-plate" src="assets/plates/${encodeURIComponent(c.id)}.png" alt="${esc(c.name)} 名牌">` : html`<div class="title-preview color-${esc(c.color.toLowerCase())}">${esc(c.name)}</div>`}<b>${esc(c.name)}</b><small>${c.distanceTarget ? `累计实际出勤 ${c.distanceTarget.toLocaleString()} km` : esc(c.description)}</small>${c.category === 'region' ? html`<small>本作解锁：完成所属区域 10 PC，无旅行伙伴</small>` : ''}${p.total ? html`<progress value="${p.done}" max="${p.total}"></progress><small>${p.unit ? p.done.toFixed(1) : p.done} / ${p.total}${p.unit ? ' km' : ''}</small>` : ''}${p.unsupported ? html`<small>尚未达成同步成绩要求</small>` : ''}${!p.total && !p.unlocked && !['region', 'stamp'].includes(c.category) ? html`<small>该活动尚未开放</small>` : ''}${/^plate-25005[1-9]$|^plate-250060$/.test(c.id)?html`<small>模拟段位四曲 LIFE 挑战合格后获取</small>`:''}<div class="collection-buttons">${['region', 'stamp'].includes(c.category) && !p.unlocked ? html`<button class="secondary-btn" data-action="collection-target" data-value="${c.id}">${active ? '已选目标' : '设为目标'}</button>` : ''}<button class="secondary-btn" data-action="equip-collection" data-value="${c.id}" ?disabled=${!p.unlocked}>${equipped ? '已装备' : p.unlocked ? '装备' : '未解锁'}</button></div></article>`;
    })}</div><div class="pagination"><span>${list.length} 件</span><button class="icon-btn" data-action="collection-page" data-value="-1" ?disabled=${page === 0} aria-label="上一页收藏">${icon('chevron-left')}</button><b>${page + 1} / ${Math.max(1, Math.ceil(list.length / size))}</b><button class="icon-btn" data-action="collection-page" data-value="1" ?disabled=${(page + 1) * size >= list.length} aria-label="下一页收藏">${icon('chevron-right')}</button></div>`;
  }
  function ranks(s,pool){
    const rank=G.friendRank(s),course=Math.max(0,...s.competition.courses);
    return html`<div class="rank-summary"><div><img src="assets/class_rank/${rank}.webp" alt="友人对战 ${G.FRIEND_RANKS[rank]}"><b>友人对战 · ${G.FRIEND_RANKS[rank]}</b><small>${s.competition.wins} 胜 / ${s.competition.losses} 负 / ${s.competition.draws} 平</small><small>本作每累计 3 胜晋升一级</small></div><div><img src="assets/course_rank/${course?course+11:0}.webp" alt="${course?G.COURSE_NAMES[course-1]:'初学者'}"><b>模拟段位 · ${course?G.COURSE_NAMES[course-1]:'未挑战'}</b><small>四曲 · 20 分钟 · ${G.allNight(s)?'计入小时费用':`¥${G.pcPrice(s)*2}`} · LIFE 300</small><small>GREAT -1 / GOOD -2 / MISS -3</small></div></div>${s.competition.lastCourse?html`<p class="form-note">最近挑战：${G.COURSE_NAMES[s.competition.lastCourse.level-1]} · ${s.competition.lastCourse.passed?'合格':'未合格'} · LIFE ${s.competition.lastCourse.life}</p>`:''}<div class="course-list">${G.COURSE_NAMES.map((name,i)=>html`<article><img src="assets/course_rank/${i+12}.webp" alt="${name}"><div><b>${name} ${s.competition.courses.includes(i+1)?'· 已合格':''}</b><small>${G.courseCharts(i+1,pool).map(c=>c.title+' '+G.displayLevel(c)).join(' / ')}</small></div><button class="secondary-btn" data-action="course" data-value="${i+1}" ?disabled=${s.phase!=='play'||s.mode!=='solo'}>查看课题</button></article>`)}</div><p class="form-note">到机厅单开后可挑战。课题为本作编排；合格可获得对应真段位名牌。友人对战在拼机时开启，双方打同一难度，比较四曲达成率合计。</p>`;
  }
  root.LifeUI = {
    ranks,
    setup,
    player,
    supplies,
    mealStatus,
    bottles,
    drinkShop,
    shop,
    chat,
    plates,
    talents,
    collections,
    partnerChoices
  };
})(window);
