(function(root){
 'use strict';let G,pool=[];
 const now=s=>(s.day-1)*1440+s.clock;
 function ensure(s){const r=s.romance;if(!r)return;r.metDay??=s.love?s.day:0;r.request??=null;r.requestCheckDay??=0;r.nextRequestDay??=s.day+1;r.pendingStory??=null;r.requestSeed??=(s.seed^0x71ac93)>>>0;
  if(s.world?.dm?.['小凛'])s.world.dm['小凛']=s.world.dm['小凛'].filter(m=>m.self||!/^.+现在 \d+ 人，大B队来了！$/.test(m.text));
  if(!s.love)return;if(!r.metDay)r.metDay=s.day;
  if(!s.npcs.some(n=>n.id==='小凛'))s.npcs.push({id:'小凛',rating:Math.max(7800,Math.min(13000,s.rating-400)),familiarity:30,activity:2,genre:'niconico & VOCALOID',tendency:'star',risk:.2,lastBoast:0,bestAchievement:0,hesitateUntil:0,career:'student',nightOwl:false,lifeEvent:'',playChatDay:0});
 }
 function random(s){const r=s.romance;r.requestSeed=(Math.imul(r.requestSeed,1664525)+1013904223)>>>0;return r.requestSeed/4294967296;}
 function arcade(s){if(!s.love||s.loveFailed||!s.city?.arcades||s.day%4===0)return null;const rest=G.dayInfo(s).rest;if(s.clock<(rest?720:1080)||s.clock>=(rest?1260:1290))return null;const places=[...s.city.arcades,...(s.city.denUnlocked?[5]:[])];return places[(s.day*7+2)%places.length]??null;}
 function status(s){const id=arcade(s);return id!==null?G.ARCADES[id].name+' · 上机与排队':s.clock<480||s.clock>=1380?'休息中':!G.dayInfo(s).rest&&s.clock>=540&&s.clock<1020?'学校 · 上课中':'今天还在忙自己的事';}
 function message(s,text,self=false){if(!s.world||!s.love)return;const list=s.world.dm['小凛']??=[];if(!self&&list.some(m=>!m.self&&m.text===text&&now(s)-((m.day-1)*1440+m.time)<120))return;list.push({id:self?s.profile.id:'小凛',text,day:s.day,time:s.clock,self});s.world.dm['小凛']=list.slice(-40);}
 function tick(s){ensure(s);if(!s.love||!s.world||s.ending)return;G.syncFriends(s);s.world.life['小凛']=status(s);const r=s.romance;
  if(r.request?.status==='active'&&now(s)>r.request.deadline){r.request.status='expired';message(s,'之前那首歌先放着吧，不急。下次见面再一起看看。');}
  if(s.loveFailed||r.request?.status==='active'||s.day<r.nextRequestDay||r.requestCheckDay===s.day||s.clock<600||s.clock>=1320||!pool.length)return;
  r.requestCheckDay=s.day;if(random(s)>=.35||now(s)+4320>=G.DAYS*1440)return;
  let choices=pool.filter(c=>c.genre==='niconico & VOCALOID'&&!G.isUtage(c)&&Math.abs(c.ds-G.baseAbility(s,c))<=.65&&Math.abs(G.effectiveDifficulty(s,c)-G.baseAbility(s,c))<=.85);
  const fresh=choices.filter(c=>(s.records[G.key(c)]?.achievement||0)<100);if(fresh.length)choices=fresh;if(!choices.length)return;
  const c=choices[Math.floor(random(s)*choices.length)];r.request={key:G.key(c),title:c.title,index:c.index,ds:c.ds,issuedAt:now(s),deadline:now(s)+4320,status:'active',achievement:null};r.nextRequestDay=s.day+5;
  message(s,`最近在练《${c.title}》${['BASIC','ADVANCED','EXPERT','MASTER','Re:MASTER'][c.index]}。你能在三天内打到鸟，再教教我那段吗？不用勉强，先按自己的状态来。`);
 }
 function afterPlay(s,results){const q=s.romance.request;if(!q||q.status!=='active')return;if(now(s)>q.deadline){tick(s);return;}const r=results.find(c=>G.key(c)===q.key&&c.achievement>=100);if(!r)return;q.status='completed';q.achievement=r.achievement;s.romance.trust=Math.min(100,s.romance.trust+3);message(s,`《${q.title}》真的打到鸟了！谢谢你愿意陪我练，下次见面教我看看。`);G.log(s,'完成小凛的教学请求：'+q.title+'，好感 +3。','heart');}
 function reply(s,text){if(/请求|期限|教|任务/.test(text)){const q=s.romance.request;return q?.status==='active'?`想请你帮我看《${q.title}》。按刚才说的难度打到鸟就好，时间到 ${G.dateISO({day:Math.floor(q.deadline/1440)+1})} ${G.time(q.deadline%1440)}。`:q?.status==='completed'?'上次那首谢谢你。先别急着练新的，今天也可以聊点别的。':'最近还没有卡住的歌。有想练的 V 家曲再一起挑吧。';}if(/在哪|出勤|拼机/.test(text))return arcade(s)!==null?`我在${G.ARCADES[arcade(s)].name}，刚好想开几首 V 家曲。你到了的话可以一起拼机。`:'这会儿我不在机厅，等有空再约，别白跑一趟。';if(/累|困|睡/.test(text))return '先休息吧，别为了成绩硬撑。我也会记得让手腕歇一歇。';if(/v家|vocal|初音|曲风|歌/i.test(text))return '我比较喜欢 V 家曲。熟悉的旋律打起来很安心，但有些停顿还是会抢拍。';if(/谢谢|感谢/.test(text))return '我也很开心。下次除了打歌，也聊聊你最近的生活吧。';const options=['今天有一段旋律一直在脑子里。等见面了放给你听。','刚把今天的事情忙完，你那边还顺利吗？','今天先不追分了，想慢慢打几首喜欢的歌。'];const recent=s.world.dm['小凛']||[];return options.find(t=>!recent.slice(-6).some(m=>m.text===t))||'嗯，我在听。';}
 function chat(s,text){message(s,text,true);message(s,reply(s,text));if(!s.loveFailed&&s.love<G.EVENTS.length&&s.romance.lastContact!==s.day){s.romance.trust=Math.min(100,s.romance.trust+1);s.romance.lastContact=s.day;}}
 function queueStory(s){if(s.romance.pendingStory!==null)return;s.romance.pendingStory=s.love;message(s,G.EVENTS[s.love].text);}
 function openStory(s){if(!['home','play','meal'].includes(s.phase)||!G.canSpendTime(s,15)||G.timeChargeReason(s,15)||s.phase==='play'&&s.clock+15>G.availableUntil(s)||s.day<s.romance.nextDay||s.romance.pendingStory!==s.love||s.ending||s.school.pending||s.event!==null||s.videoEvent||s.city.encounter||s.world.notice||s.world.mahjong.active)throw Error('请先完成当前行动。');s.event=s.love;}
 function pair(s){if(s.phase!=='play'||arcade(s)!==s.arcade||s.ending||s.school.pending||s.videoEvent||s.city.encounter||s.event!==null||s.world.notice||s.world.mahjong.active)throw Error('小凛现在不在这家机厅。');G.setMode(s,'pair');s.partner=s.npcs.findIndex(n=>n.id==='小凛');s.partnerSongs=null;s.friendship=false;G.log(s,'和小凛一起拼机，她在挑喜欢的 V 家曲。','heart');}
 function valid(s){const r=s.romance,q=r?.request;return !!r&&Number.isInteger(r.metDay)&&r.metDay>=0&&r.metDay<=s.day&&Number.isInteger(r.requestSeed)&&r.requestSeed>=0&&r.requestSeed<=4294967295&&Number.isInteger(r.requestCheckDay)&&r.requestCheckDay>=0&&r.requestCheckDay<=s.day&&Number.isInteger(r.nextRequestDay)&&r.nextRequestDay>=1&&r.nextRequestDay<=G.DAYS+5&&(r.pendingStory===null||Number.isInteger(r.pendingStory)&&r.pendingStory===s.love&&r.pendingStory>0&&r.pendingStory<8)&&(!q||typeof q.key==='string'&&/^\d+:\d$/.test(q.key)&&typeof q.title==='string'&&q.title.length<300&&Number.isInteger(q.index)&&q.index>=0&&q.index<=4&&Number.isFinite(q.ds)&&q.ds>0&&q.ds<=20&&Number.isInteger(q.issuedAt)&&q.issuedAt>=0&&Number.isInteger(q.deadline)&&q.deadline-q.issuedAt===4320&&q.deadline<=G.DAYS*1440&&(!pool.length||pool.some(c=>G.key(c)===q.key&&c.genre==='niconico & VOCALOID'&&c.title===q.title&&c.index===q.index&&c.ds===q.ds))&&['active','completed','expired'].includes(q.status)&&(q.status==='completed'?Number.isFinite(q.achievement)&&q.achievement>=100&&q.achievement<=101:q.achievement===null));}
 function install(api){G=api;Object.assign(api,{ensureLin:ensure,linArcade:arcade,linStatus:status,linMessage:message,linTick:tick,linAfterPlay:afterPlay,chatLin:chat,queueLinStory:queueStory,openLinStory:openStory,pairWithLin:pair,setLinPool:p=>{pool=p;}});}
 const api={install,valid};if(typeof module!=='undefined')module.exports=api;else root.LinLife=api;
})(globalThis);
