const path=require('node:path'),fs=require('node:fs'),assert=require('node:assert/strict'),vm=require('node:vm');
const {pathToFileURL}=require('node:url'),{createRequire}=require('node:module');
const runtime=createRequire('C:/Users/ADMIN/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/browser-runtime.js');
const {chromium}=runtime('playwright'),G=require('../engine.js'),output=path.join(__dirname,'../artifacts');
fs.mkdirSync(output,{recursive:true});
async function main(){
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(pathToFileURL(path.join(__dirname,'../index.html')).href);await page.locator('#setup-form').waitFor();
  async function screenshot(name,fullPage=true){await page.locator('#toast').evaluate(el=>el.classList.remove('show'));await page.locator('img').evaluateAll(imgs=>imgs.forEach(i=>i.loading='eager'));await page.waitForFunction(()=>[...document.images].every(i=>i.complete));await page.screenshot({path:path.join(output,name),fullPage,animations:'disabled'});}
  async function load(s){if(s.version===2)s.setupDone=true;const target=path.join(output,'ui-fixture.json');fs.writeFileSync(target,JSON.stringify(s));await page.getByRole('button',{name:'存档与设置'}).click();await page.locator('#import-save').setInputFiles(target);await page.waitForSelector('#import-save',{state:'detached'});}
  async function noOverflow(label){assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${label} horizontal overflow`);}
  async function setup(job='student',blank=false){await page.locator('#player-name').fill(blank?'':'小林');await page.locator('#player-id').fill(blank?'':'今晚一起出勤');await page.locator(`input[name="career"][value="${job}"]`).check();await page.locator('input[name="talent"]').first().check();await page.getByRole('button',{name:'开始春季生活'}).click();await page.locator('.action-card').first().waitFor();}
  await screenshot('life-setup.png');await page.setViewportSize({width:390,height:844});await noOverflow('setup mobile');await screenshot('life-setup-mobile.png');await page.setViewportSize({width:1008,height:960});await setup('student',true);assert.ok((await page.locator('.player-identity').innerText()).includes('Maimai'));assert.ok((await page.locator('.player-identity').innerText()).includes('神秘人'));assert.equal(await page.locator('.mainland-rating>img').getAttribute('src'),'assets/rating/wahlap/rating_base_normal.png');assert.equal(await page.locator('.mainland-rating-digits img').count(),5);assert.ok(await page.locator('.mainland-rating.tier-1').isVisible());assert.equal(await page.locator('.player-title').evaluate(el=>getComputedStyle(el).borderTopLeftRadius),'999px');
  assert.equal(await page.locator('.scene-image').count(),0);assert.equal(await page.locator('.page-heading').count(),0);
  await screenshot('spring-home.png');
  await load(G.create('worker',42));assert.ok((await page.locator('.money').innerText()).includes('6000'));assert.equal(await page.locator('[data-action="daily"][data-value="work"]').count(),0);
  await load(G.create('student',42));
  assert.equal(await page.locator('[data-action="job"]').count(),0);assert.ok((await page.locator('.free-day').innerText()).includes('今日无课'));assert.ok((await page.locator('.ledger').innerText()).includes('每月 1 日发放'));
  await page.getByRole('button',{name:'查看舞萌群'}).click();assert.equal(await page.locator('.chat-message').count(),3);await page.getByRole('textbox',{name:'群聊消息'}).fill('今晚一起拼机吧');await page.getByRole('button',{name:'发送消息',exact:true}).click();assert.equal(await page.locator('.chat-message.self').count(),1);await page.getByRole('textbox',{name:'群聊消息'}).fill('@bot');await page.getByRole('button',{name:'发送消息',exact:true}).click();assert.ok((await page.locator('.chat-window').innerText()).includes('快捷指令'));await page.getByRole('textbox',{name:'群聊消息'}).fill('jk');await page.getByRole('button',{name:'发送消息',exact:true}).click();assert.ok((await page.locator('.chat-window').innerText()).includes('台机组'));await page.getByRole('textbox',{name:'群聊消息'}).fill('f8fq');await page.getByRole('button',{name:'发送消息',exact:true}).click();assert.equal(await page.locator('.chat-message p').last().innerText(),'不要念辣个');await screenshot('life-chat.png',false);await page.getByRole('button',{name:'关闭',exact:true}).click();
  await page.getByRole('button',{name:'名牌与解锁进度'}).click();assert.equal(await page.locator('.collection-item').count(),18);assert.ok((await page.locator('.pagination').innerText()).includes('72 件'));await page.locator('[data-action="collection-status"][data-value="unlocked"]').click();assert.equal(await page.locator('.collection-item').count(),1);assert.ok((await page.locator('.collection-item').innerText()).includes('已装备'));await page.locator('[data-action="collection-status"][data-value="locked"]').click();assert.equal(await page.locator('[data-action="equip-collection"]:not([disabled])').count(),0);assert.ok((await page.locator('.pagination').innerText()).includes('71 件'));await page.locator('[data-action="collection-status"][data-value="all"]').click();await screenshot('expansion-plates.png',false);await page.locator('[data-action="collection-tab"][data-value="title"]').click();await page.getByRole('textbox',{name:'搜索收藏品'}).fill('覚醒');assert.equal(await page.locator('.collection-item').count(),0);await page.getByRole('textbox',{name:'搜索收藏品'}).fill('徒步来哒');assert.ok((await page.locator('.collection-item').innerText()).includes('0.0 / 100 km'));await page.getByRole('textbox',{name:'搜索收藏品'}).fill('评级1000');assert.ok(await page.locator('.collection-item').count()>0);await page.locator('[data-action="collection-tab"][data-value="stamp"]').click();await page.locator('[data-action="collection-target"]').first().click();assert.equal(await page.locator('[data-action="check-in"]').count(),0);assert.ok((await page.locator('.stamp-status').innerText()).includes('首次上机后自动签到'));await page.locator('[data-action="collection-tab"][data-value="region"]').click();await page.locator('[data-action="collection-target"]').first().click();await screenshot('expansion-region.png',false);for(const width of [320,390]){await page.setViewportSize({width,height:844});await noOverflow(`collections ${width}`);await screenshot(`expansion-collections-${width}.png`,false);}await page.setViewportSize({width:1008,height:960});await page.getByRole('button',{name:'关闭',exact:true}).click();
  await page.getByRole('button',{name:'购买手套'}).click();await page.locator('[data-action="buy-gloves"][data-value="sport"]').click();await page.getByRole('button',{name:'关闭',exact:true}).click();assert.ok((await page.locator('.player-status').innerText()).includes('240'));
  await page.getByRole('button',{name:'自定义头像',exact:true}).click();await page.locator('#avatar-upload').setInputFiles(path.join(__dirname,'../assets/plates/default.png'));await page.locator('.avatar-editor>img').waitFor();await page.getByRole('button',{name:'关闭',exact:true}).click();assert.ok(await page.locator('.player-avatar>img').isVisible());
  await page.getByRole('button',{name:'出发，打舞萌！',exact:false}).click();
  await page.locator('[data-action="mode"][data-value="pair"]').click();
  await page.getByRole('button',{name:/骑共享/}).click();await page.getByRole('button',{name:/自带白水/}).click();
  await page.getByRole('button',{name:'自选曲目'}).click();await page.getByRole('textbox',{name:'搜索曲名、艺术家或曲目 ID'}).fill('PANDORA');
  await page.locator('.song-group').first().locator('.chart-cell').nth(3).click();
  await page.locator('.selection-slots [data-value="1"]').click();await page.getByRole('textbox',{name:'搜索曲名、艺术家或曲目 ID'}).fill('PANDORA');await page.locator('.song-group').first().locator('.chart-cell').last().click();
  assert.equal(await page.locator('.selection-slots button').count(),2);
  if(await page.locator('[data-action="queue"]').count())await page.locator('[data-action="queue"]').click();assert.ok(await page.locator('.partner-line').isVisible());await page.locator('[data-partner-slot="0"]').selectOption('0');await screenshot('expansion-partner.png',true);for(const width of [320,390]){await page.setViewportSize({width,height:844});await noOverflow(`partner ${width}`);await page.locator('[data-partner-slot="0"]').scrollIntoViewIfNeeded();await screenshot(`expansion-partner-${width}.png`,false);}await page.setViewportSize({width:1008,height:960});await page.reload();await page.getByRole('button',{name:'继续出勤',exact:false}).click();assert.equal(await page.locator('[data-partner-slot="0"]').inputValue(),'0');assert.ok((await page.locator('.selection-slots').innerText()).includes('PANDORA'));await page.getByRole('button',{name:'投币上机 · ¥6'}).click();assert.equal(await page.locator('.performance-results>article').count(),4);assert.equal(await page.locator('.judgements').count(),4);
  await screenshot('life-play.png',false);assert.equal(await page.locator('[data-action="arcade-rest"]').count(),0);await page.locator('[data-action="queue"]').click();await page.locator('[data-action="supplies"]').last().click();await page.locator('[data-action="refill"][data-value="tea"]').click();assert.ok((await page.locator('.supply-strip').innerText()).includes('600 ml'));
  await page.getByRole('button',{name:/结束上机，去吃饭/}).click();await page.getByRole('button',{name:/回家吃饭/}).click();
  assert.ok((await page.locator('.calendar-date').innerText()).includes('2026-03-01'));assert.notEqual(await page.locator('.clock-display>b').innerText(),'08:00');
  await page.reload();assert.ok((await page.locator('.calendar-date').innerText()).includes('2026-03-01'));await page.getByRole('button',{name:'名牌与解锁进度'}).click();await page.locator('[data-action="collection-tab"][data-value="title"]').click();await page.getByRole('textbox',{name:'搜索收藏品'}).fill('徒步来哒');assert.ok((await page.locator('.collection-item').innerText()).includes('3.6 / 100 km'));await page.getByRole('button',{name:'关闭',exact:true}).click();await page.getByRole('button',{name:'名牌与解锁进度'}).click();await page.locator('[data-action="collection-tab"][data-value="stamp"]').click();assert.ok((await page.locator('.stamp-status').innerText()).includes('今日已自动签到'));assert.ok((await page.locator('.collection-item').first().innerText()).includes('2 / 10'));await page.getByRole('button',{name:'关闭',exact:true}).click();
  await page.getByRole('button',{name:'B50',exact:true}).click();await page.locator('[data-action="best-style"][data-value="image"]').click();await page.waitForFunction(()=>document.querySelector('[data-b50-image="current"]')?.naturalWidth===1500);await screenshot('update-b50.png');await page.getByRole('button',{name:'日常',exact:true}).click();await page.getByRole('button',{name:'查看舞萌群'}).click();await page.getByRole('textbox',{name:'群聊消息'}).fill('B50');await page.getByRole('button',{name:'发送消息',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.chat-b50')?.naturalWidth===1500);await screenshot('update-bot-b50.png',false);await page.getByRole('button',{name:'查看完整 B50 成绩图',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.b50-image-view img')?.naturalWidth===1500);await page.getByRole('button',{name:'关闭',exact:true}).click();assert.ok(await page.locator('.chat-window').isVisible());await page.getByRole('button',{name:'关闭',exact:true}).click();await page.getByRole('button',{name:'睡觉'}).click();assert.ok((await page.locator('.calendar-date').innerText()).includes('2026-03-02'));
  await page.locator('[data-action="class"]').first().click();assert.equal(await page.locator('.clock-display>b').innerText(),'11:00');
  await page.getByRole('button',{name:'逃课 通识选修'}).click();await page.getByRole('button',{name:'确认逃课'}).click();assert.equal(await page.locator('.clock-display>b').innerText(),'11:00');
  await page.getByRole('button',{name:'曲库',exact:true}).click();await page.getByRole('textbox',{name:'搜索曲名、艺术家或曲目 ID'}).fill('True Love Song');
  assert.equal(await page.locator('.song-group').count(),1);assert.equal(await page.locator('.chart-cell').count(),4);assert.equal(await page.locator('.song-group-header>div>small').innerText(),'maimai · 150 BPM · ID 8');
  assert.deepEqual(await page.locator('.chart-cell>span:first-child').allTextContents(),['BASIC ','ADVANCED ','EXPERT ','MASTER ']);
  await page.getByRole('textbox',{name:'搜索曲名、艺术家或曲目 ID'}).fill('Starlight Disco');
  assert.ok(await page.locator('.song-group .type-label.DX').count()>=1);assert.ok(await page.locator('.song-group .type-label.SD').count()>=1);
  await page.getByRole('textbox',{name:'搜索曲名、艺术家或曲目 ID'}).fill('');
  await page.getByRole('textbox',{name:'搜索曲名、艺术家或曲目 ID'}).fill('12+');assert.ok((await page.locator('.chart-cell>b').allTextContents()).every(t=>t==='12+'));await page.getByRole('textbox',{name:'搜索曲名、艺术家或曲目 ID'}).fill('');await page.locator('#song-era').selectOption('ORANGE PLUS');assert.ok((await page.locator('.song-group-header>div>small').allTextContents()).every(t=>t.includes('ORANGE PLUS')));await page.locator('#song-era').selectOption('all');await page.locator('#song-utage').selectOption('only');assert.ok((await page.locator('.song-group h3').allTextContents()).every(t=>t.trim().startsWith('[')));await page.locator('#song-utage').selectOption('exclude');assert.deepEqual(await page.locator('#song-pattern option').allTextContents(),['全部配置','星星谱','键盘谱','鬼歌','吃分推荐']);await page.locator('#song-pattern').selectOption('star');await screenshot('expansion-library.png');await page.locator('#song-pattern').selectOption('all');
  for(const width of [320,390,561,798,1008,1280,1920]){
   await page.setViewportSize({width,height:960});await noOverflow(`library ${width}`);
   if(width===798)await screenshot('spring-library-798.png',false);
   if(width===390)await screenshot('spring-library-mobile.png',false);
   await page.getByRole('button',{name:'日常',exact:true}).click();await noOverflow(`home ${width}`);
   if(width===798)await screenshot('spring-home-798.png',false);
   if(width===390||width===561)await screenshot(`life-home-${width}.png`,false);if(width===1008)await screenshot('life-home.png',false);
   await page.getByRole('button',{name:'曲库',exact:true}).click();
  }
  await page.setViewportSize({width:798,height:960});await page.getByRole('button',{name:'日常',exact:true}).click();
  const school=G.create('student',42);G.academicChange(school,-70);await load(school);await page.getByRole('button',{name:'回应老师'}).click();assert.ok((await page.locator('.academic-line').innerText()).includes('约谈 1/3'));
  await page.getByRole('button',{name:/补习 2 小时/}).click();await page.getByRole('button',{name:/补习 2 小时/}).click();assert.ok((await page.locator('.academic-line').innerText()).includes('学业正常'));
  for(const ending of ['good','love','broke','burnout','ordinary','rent','dropout']){
   const s=G.create();s.ending=ending;s.phase='ending';await load(s);await page.locator('.ending-art').waitFor();
   if(ending==='dropout')await screenshot('spring-dropout.png',false);
   await page.getByRole('button',{name:'开启新故事'}).click();await page.getByRole('button',{name:'确认重新开始'}).click();await setup();
  }
  const cctx={window:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../data/music.js'),'utf8'),cctx);const cp=G.charts(cctx.window.MUSIC_DATA),romance=G.create();romance.visits=1;G.startTrip(romance);G.travel(romance,'bike',1);G.drink(romance,'water');if(romance.queueUntil>romance.clock)G.waitQueue(romance);G.play(romance,G.recommend(romance,cp),cp);G.finishPlay(romance);assert.equal(romance.event,0);await load(romance);await page.getByRole('button',{name:'“没有，一起排吧。”'}).click();await page.getByRole('button',{name:/回家吃饭/}).click();
  const old={version:1,job:'student',seed:42,day:13,money:128,mood:64,skill:11.64,records:{},started:true,visits:6,credits:10,love:1,loveFailed:false,nextLoveVisit:8};await load(old);assert.ok((await page.locator('.calendar-date').innerText()).includes('2026-03-13'));assert.ok((await page.locator('.money').innerText()).includes('128'));assert.equal(await page.locator('.skill-strip>span b').first().innerText(),'11.64');
  const late=G.create('worker',42);late.nightActive=true;late.day=2;late.clock=180;late.setupDone=true;await load(late);await screenshot('expansion-late.png',false);await page.getByRole('button',{name:'睡觉'}).click();assert.equal(await page.locator('.clock-display>b').innerText(),'11:00');assert.ok((await page.locator('.sleep-debuff').innerText()).includes('熬夜 3 级'));assert.ok((await page.locator('.schedule-list').innerText()).includes('旷工'));

  const full=G.create('grinder',123);full.profile.id='完整B50检查';for(const group of [cp.filter(c=>!c.isNew&&!c.utage).slice(-35),cp.filter(c=>c.isNew&&!c.utage).slice(-15)])for(const c of group)full.records[G.key(c)]={...c,achievement:97.1234,ra:G.chartRating(c.ds,97.1234),combo:'FC',bestCombo:'FC'};G.recalculate(full);await load(full);await page.getByRole('button',{name:'B50',exact:true}).click();await page.locator('[data-action="best-style"][data-value="image"]').click();await page.waitForFunction(()=>document.querySelector('[data-b50-image="current"]')?.naturalWidth===1500);
  const png=await page.locator('[data-b50-image="current"]').getAttribute('src');fs.writeFileSync(path.join(output,'update-full-b50.png'),Buffer.from(png.split(',')[1],'base64'));
  for(const width of [320,390]){await page.setViewportSize({width,height:844});await noOverflow('B50 '+width);await screenshot('update-b50-'+width+'.png',false);}
  const video=G.create('grinder',55);video.skills.star=video.skills.key=video.skills.reading=12;for(let i=0;i<6&&!video.videoEvent;i++)G.watchVideos(video);assert.ok(video.videoEvent);const outcome=video.videoEvent.outcome;await load(video);await screenshot('update-video-mobile.png',false);await page.getByRole('button',{name:outcome==='clear'?'大彻大悟':'似懂非懂',exact:true}).click();assert.equal(await page.locator('[data-action="learn-video"]').count(),0);
  await page.getByRole('button',{name:'日常',exact:true}).click();await page.getByRole('button',{name:'娱乐',exact:false}).click();assert.equal(await page.getByRole('button',{name:'在家小憩',exact:false}).count(),0);assert.ok(await page.locator('[data-action="watch-videos"]').isVisible());await page.getByRole('button',{name:'关闭',exact:true}).click();

  const hidden=cp.find(c=>c.tags.includes('拆弹'));let eventState;
  for(let i=1;i<30;i++){eventState=G.create('grinder',i);G.startTrip(eventState);G.travel(eventState,'bike',0);G.drink(eventState,'water');if(eventState.queueUntil>eventState.clock)G.waitQueue(eventState);eventState.skills.star=eventState.skills.key=eventState.skills.reading=1;G.play(eventState,[hidden,hidden,hidden],cp);if(eventState.last.results.some(r=>r.segmentEvent&&!r.segmentEvent.passed))break;}
  await load(eventState);await page.getByRole('button',{name:'继续出勤',exact:false}).click();assert.ok(await page.locator('.segment-outcome.failed').count()>0);await page.setViewportSize({width:390,height:844});await noOverflow('segment results');await page.locator('.segment-outcome.failed').first().scrollIntoViewIfNeeded();await screenshot('review-segment-mobile.png',false);await page.getByRole('button',{name:'关闭',exact:true}).click();
  await page.getByRole('button',{name:'曲库',exact:true}).click();await page.getByRole('textbox',{name:'搜索曲名、艺术家或曲目 ID'}).fill(hidden.title);await page.locator(`[data-action="chart-detail"][data-value="${G.key(hidden)}"]`).click();assert.equal(await page.locator('.chart-patterns').count(),0);await page.getByRole('button',{name:'关闭',exact:true}).click();
  const crowded=G.create('grinder',42);crowded.clock=1200;crowded.people=18;await load(crowded);await page.getByRole('button',{name:'日常',exact:true}).click();await page.getByRole('button',{name:'查看舞萌群'}).click();assert.ok((await page.locator('.chat-window').innerText()).includes('大B队来了'));await screenshot('review-crowded-chat.png',false);await page.getByRole('button',{name:'关闭',exact:true}).click();
  const loaded=await page.locator('img').evaluateAll(imgs=>imgs.every(i=>i.complete&&i.naturalWidth>0));assert.ok(loaded);assert.deepEqual(errors,[]);
  console.log(JSON.stringify({status:'pass',consoleErrors:errors,checks:['removed illustration/headlines','job economics','worker no side job','paired four-song round','two user-selected charts','judgements and combos','same-day return','save reload','class and skip','grouped difficulties and SD/DX','real covers and version names','320-1920 responsive layouts','teacher and academic recovery','seven endings','romance event','legacy save migration','71 achievement plates and titles','stamp and region unlocks','custom avatar','independent partner difficulty persists','era and utage filters','midnight debuff and work absence','320/390 collection and partner dialogs','bot help/crowd/B50 PNG','full 50-chart image and 320/390 layouts','hand-video event and no manual rest','single-slot selection persists','integer-plus search']},null,2));
 }finally{await browser.close();}
}
main().catch(e=>{console.error(e);process.exit(1);});
