const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{pathToFileURL}=require('node:url');
const runtime=require('node:module').createRequire('C:/Users/ADMIN/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/browser-runtime.js'),{chromium}=runtime('playwright'),G=require('../engine');
const ctx={window:{}};vm.runInNewContext(fs.readFileSync(require.resolve('../data/music.js'),'utf8'),ctx);const pool=G.charts(ctx.window.MUSIC_DATA);
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const page=await browser.newPage({viewport:{width:821,height:698}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addLocatorHandler(page.locator('[data-action="meal-later"]'),async()=>{await page.locator('[data-action="meal-later"]').click();});
 await page.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href);await page.locator('input[name="talent"]').first().check();await page.getByRole('button',{name:'开始春季生活'}).click();await page.locator('[data-action="intro-skip"]').click();
 async function load(s){s.setupDone=true;const file=path.resolve(__dirname,'../artifacts/city-fixture.json');fs.writeFileSync(file,JSON.stringify(s));await page.getByRole('button',{name:'存档与设置'}).click();await page.locator('#import-save').setInputFiles(file);await page.waitForSelector('#import-save',{state:'detached'});}
 async function close(){await page.getByRole('button',{name:'关闭',exact:true}).click();}
 async function shot(name){await page.screenshot({path:path.resolve(__dirname,'../artifacts/'+name+'.png')});}
 const s=G.create('grinder',42);await load(s);
 await page.evaluate(()=>scrollTo(0,400));assert.ok(Math.abs(await page.locator('.date-toolbar').evaluate(el=>el.getBoundingClientRect().top))<2);await page.evaluate(()=>scrollTo(0,0));
 const nav=await page.locator('.nav-item.active').evaluate(el=>({height:el.getBoundingClientRect().height,bottom:getComputedStyle(el,'::after').bottom}));assert.ok(nav.height>50);assert.equal(nav.bottom,'10px');
 assert.equal(await page.locator('.nameplate-top [data-action="plates"]').count(),0);assert.match(await page.locator('.condition').first().innerText(),/今日舞萌状态/);
 await page.getByRole('button',{name:'查看舞萌群'}).click();
 async function send(text){await page.getByRole('textbox',{name:'群聊消息'}).fill(text);await page.getByRole('button',{name:'发送消息',exact:true}).click();}
 await send('运势');const fortune=await page.locator('.chat-message p').last().innerText();await send('jrrp');assert.equal(await page.locator('.chat-message p').last().innerText(),fortune);
 await send('jk');await send('几卡');assert.equal(await page.locator('.clock-display>b').innerText(),'08:02');await send('塔罗');assert.ok(['08:04','08:05'].includes(await page.locator('.clock-display>b').innerText()));await shot('city-bot');await close();
 await page.getByRole('button',{name:'娱乐',exact:false}).click();assert.equal(await page.locator('[data-action="explore"]').count(),8);
 for(const width of [320,390,821]){await page.setViewportSize({width,height:698});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 await page.locator('[data-action="explore"][data-value="shamian"]').scrollIntoViewIfNeeded();await shot('city-entertain');await page.locator('[data-action="explore"][data-value="shamian"]').click();
 if(await page.locator('[data-action="city-answer"]').count())await page.locator('[data-action="city-answer"][data-value="0"]').click();
 assert.match(await page.locator('.recent-section').innerText(),/沙面岛/);
 await page.getByRole('button',{name:'名牌与解锁进度'}).click();await page.getByRole('textbox',{name:'搜索收藏品'}).fill('舞舞');assert.ok(await page.locator('.collection-item').count()>0);await shot('city-maimai-plates');
 await page.locator('[data-action="ranks"]').click();assert.equal(await page.locator('.course-list article').count(),10);assert.equal(await page.locator('[data-action="course"]:not([disabled])').count(),0);await close();
 const empty=G.create('grinder',42);G.startTrip(empty);G.travel(empty,'bike',1);G.drink(empty,'water');empty.people=0;empty.crowdShift=0;await load(empty);await page.getByRole('button',{name:'继续出勤',exact:false}).click();assert.ok(await page.locator('[data-action="mode"][data-value="pair"]').isDisabled());assert.equal(await page.locator('.partner-line').count(),0);await shot('city-empty-arcade');await close();
 const active=G.create('grinder',42);active.people=18;active.skills={star:22,key:22,reading:22};G.startTrip(active);G.travel(active,'bike',0);G.drink(active,'water');if(active.queueUntil>active.clock)G.waitQueue(active);await load(active);await page.getByRole('button',{name:'继续出勤',exact:false}).click();await page.locator('[data-action="ranks"]').click();
 for(const width of [320,390,821]){await page.setViewportSize({width,height:698});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await shot('city-ranks-'+width);}
 await page.locator('[data-action="course"][data-value="1"]').click();
 const fixed=await page.locator('[data-course-chart]').evaluateAll(els=>els.map(el=>el.dataset.courseChart));
 assert.deepEqual(fixed,Array.from(G.courseCharts(1,pool),G.key));assert.equal(await page.locator('[data-action="picker"],[data-action="pick"],[data-action="reroll"],select[data-partner-slot]').count(),0);
 assert.match(await page.locator('.supply-strip .condition').innerText(),/^今日状态：/);
 const cash=await page.locator('.player-status .money>b').innerText();
 for(const width of [320,390,1232]){await page.setViewportSize({width,height:960});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await shot('course-preview-'+width);}
 assert.equal(await page.locator('.player-status .money>b').innerText(),cash);
 await page.locator('[data-action="course-start"]').click();assert.match(await page.locator('.modal-heading').innerText(),/挑战结算/);assert.equal(await page.locator('.performance-results article').count(),4);
 assert.ok((await page.locator('.performance-score em').allTextContents()).every(x=>!x.includes('鸟')));assert.equal(await page.locator('[data-action="picker"],[data-action="reroll"]').count(),0);
 await shot('course-results');await close();await close();
 const pair=G.create('grinder',42);pair.people=18;G.startTrip(pair);G.setMode(pair,'pair');G.travel(pair,'bike',0);G.drink(pair,'water');if(pair.queueUntil>pair.clock)G.waitQueue(pair);await load(pair);await page.getByRole('button',{name:'继续出勤',exact:false}).click();const selections=await page.locator('.selection-slots button').allTextContents();await page.locator('[data-action="reroll"]').click();const changed=await page.locator('.selection-slots button').allTextContents();assert.ok(changed.every(text=>!selections.includes(text)));
 assert.match(await page.locator('.mode-status').innerText(),/当前模式：拼机/);assert.equal(await page.locator('.mode-select .selected').count(),1);
 await page.locator('[data-action="battle"]').click();await page.locator('[data-action="play"]').click();assert.ok(await page.locator('.battle-result').isVisible());assert.equal(await page.locator('.sync-result').count(),4);await page.setViewportSize({width:390,height:698});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('.battle-result').scrollIntoViewIfNeeded();await shot('city-battle');await close();
 const discovered=G.create('grinder',42);discovered.city.arcades.push(3,4);discovered.city.restaurants.push('wonton');await load(discovered);await page.getByRole('button',{name:'出发，打舞萌！',exact:false}).click();assert.equal(await page.locator('.arcade-option').count(),5);await page.locator('[data-action="arcade"][data-value="4"]').click();assert.equal(await page.locator('.arcade-option.selected').getAttribute('data-value'),'4');assert.equal(await page.locator('.selection-mark').count(),0);assert.match(await page.locator('.mode-status').innerText(),/当前模式：单开/);await shot('selection-indicators');await page.getByRole('button',{name:/公共交通/}).click();await page.locator('[data-action="pack-drink"][data-value="water"]').click();await page.locator('[data-action="drinks-ready"]').click();await page.locator('[data-action="finish"]').click();assert.ok(await page.locator('[data-action="meal"][data-value="wonton"]').isVisible());await shot('city-restaurant');await page.locator('[data-action="meal-destination"][data-value="arcade"]').click();assert.equal(await page.locator('[data-action="meal"][data-value="home"]').count(),0);await shot('meal-return-choice');await page.locator('[data-action="meal"][data-value="wonton"]').click();assert.ok(await page.locator('.supply-strip').isVisible());assert.match(await page.locator('.recent-section').innerText(),/吃得很满足/);
 await page.locator('[data-action="finish"]').click();await page.locator('[data-action="resume-play"]').click();assert.ok(await page.locator('.supply-strip').isVisible());
 await page.locator('[data-action="finish"]').click();await page.locator('[data-action="meal"][data-value="home"]').click();assert.ok(await page.getByRole('button',{name:'出发，打舞萌！',exact:false}).isVisible());
 for(const job of ['student','worker']){const missed=G.create(job,42);missed.day=2;missed.clock=180;missed.nightActive=true;G.sleep(missed);await load(missed);const text=await page.locator('.schedule-list').innerText();assert.ok(text.includes(job==='student'?'旷课':'旷工'));assert.ok(!text.includes(job==='student'?'旷工':'旷课'));}
 assert.deepEqual(errors,[]);console.log('PASS: Guangzhou activities and discoveries, bot timings, empty pairing, course unlock, battle/sync, mainland art, 320/390/821px layouts.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
