const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url');
const runtime=require('node:module').createRequire('C:/Users/ADMIN/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/browser-runtime.js'),{chromium}=runtime('playwright'),G=require('../engine');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addLocatorHandler(page.locator('[data-action="meal-later"]'),async()=>{await page.locator('[data-action="meal-later"]').click();});
 await page.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href);await page.locator('input[name="talent"]').first().check();await page.getByRole('button',{name:'开始春季生活'}).click();await page.locator('[data-action="intro-skip"]').click();
 const s=G.create('grinder',42);s.setupDone=true;s.guide.claimed=['rating-12000','practice'];delete s.guide.rewardVersion;s.money=5000;s.day=2;s.clock=45;s.nightActive=true;s.people=0;
 const file=path.resolve(__dirname,'../artifacts/den-fixture.json');fs.writeFileSync(file,JSON.stringify(s));await page.getByRole('button',{name:'存档与设置'}).click();await page.locator('#import-save').setInputFiles(file);await page.waitForSelector('#import-save',{state:'detached'});
 const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('attendance-simulator-v2')));
 async function shot(name){await page.locator('#toast').evaluate(el=>el.classList.remove('show'));await page.screenshot({path:path.resolve(__dirname,'../artifacts/den-'+name+'.png'),animations:'disabled'});}
 await page.locator('[data-action="guide"]').click();assert.match(await page.locator('.goal-list').innerText(),/读谱力 \+0.25/);assert.match(await page.locator('.goal-list').innerText(),/24 小时营业/);await shot('rewards');await page.getByRole('button',{name:'关闭',exact:true}).click();
 await page.locator('[data-action="attend"]').click();assert.equal(await page.locator('.arcade-option.selected').getAttribute('data-value'),'5');assert.match(await page.locator('.phone-location').innerText(),/3 \/ 5 家 · 特殊场所 1 家/);assert.match(await page.locator('.den-price').innerText(),/¥30 \/ 小时/);
 for(const width of [320,390]){await page.setViewportSize({width,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok(await page.locator('.modal').evaluate(el=>el.scrollWidth<=el.clientWidth+1));}await shot('travel');
 const fare=G.transportOptions(5).find(t=>t.id==='taxi').cost;await page.getByRole('button',{name:/打车/}).click();await page.locator('[data-action="pack-drink"][data-value="water"]').click();await page.locator('[data-action="drinks-ready"]').click();assert.equal((await saved()).money,5000-fare-35);
 if(await page.locator('[data-action="queue"].primary-btn').count())await page.locator('[data-action="queue"].primary-btn').click();assert.match(await page.locator('.modal-heading').innerText(),/全天营业/);assert.match(await page.locator('.queue-info').innerText(),/¥30 \/ 小时/);await page.locator('[data-action="play"]').click();assert.equal((await saved()).money,5000-fare-35);assert.equal((await saved()).day,2);await shot('night-play');
 await page.getByRole('button',{name:'关闭',exact:true}).click();await page.reload();await page.locator('[data-action="attend"]').click();assert.match(await page.locator('.queue-info').innerText(),/¥30/);await page.locator('[data-action="finish"]').click();await page.locator('[data-action="meal"][data-value="home"]').click();assert.equal((await saved()).phase,'home');await page.locator('[data-action="chat"]').click();await page.locator('#chat-message').fill('jk');await page.getByRole('button',{name:'发送消息',exact:true}).click();assert.match(await page.locator('.chat-window').innerText(),/不眠音游窝/);assert.deepEqual(errors,[]);console.log('PASS: migrated rewards, separate special venue, mobile pricing, night travel/play, persistence and bot listing.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
