const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),G=require('../engine');
const ctx={window:{}};vm.runInNewContext(fs.readFileSync(require.resolve('../data/music.js'),'utf8'),ctx);const pool=G.charts(ctx.window.MUSIC_DATA);
test('closed collections and legacy DX conditions are removed, with old equipment migrated',()=>{
 const s=G.create(),data=require('../data/expansion');
 const removed=data.collections.filter(c=>!G.collectionItem(c.id));
 assert.equal(removed.filter(c=>c.kind==='plate').length,50);assert.equal(removed.filter(c=>c.kind==='title').length,342);
 for(const c of G.COLLECTIONS){assert.ok(!/maimai\s*でらっくすで/i.test(c.description));const p=G.collectionProgress(s,c,pool);assert.ok(p.total>0||p.unlocked,c.id);}
 s.profile.plate='plate-3';s.profile.title='title-12';s.collection.unlocked=['plate-3','title-12','title-1'];s.collection.stampTarget='plate-3';
 const oldMoney=s.money,restored=G.migrate(JSON.parse(JSON.stringify(s)));
 assert.equal(restored.profile.plate,'default');assert.equal(restored.profile.title,'title-1');assert.equal(restored.collection.stampTarget,null);assert.deepEqual(restored.collection.unlocked,['title-1']);assert.equal(restored.money,oldMoney);assert.ok(G.validate(restored));
 assert.throws(()=>G.equipCollection(restored,'title-12',pool));assert.throws(()=>G.collectionTarget(restored,'plate-3'));
});
function ready(job='grinder'){const s=G.create(job,42);s.clock=600;s.people=18;G.startTrip(s);G.setMode(s,'pair');G.travel(s,'bike',1);G.drink(s,'water');if(s.queueUntil>s.clock)G.waitQueue(s);return s;}
test('song titles require every requested song and difficulty in the current library',()=>{
 const songs=new Map(ctx.window.MUSIC_DATA.map(song=>[song.id,song]));
 for(const title of G.COLLECTIONS.filter(c=>c.kind==='title'))for(const rule of title.required)for(const required of rule.songs){
  const song=songs.get(required.id);assert.ok(song,title.id);assert.equal(song.title,required.title);
  assert.ok(rule.difficulties?.length?rule.difficulties.every(i=>song.ds[i]>0):song.ds.some(ds=>ds>0),title.id);
 }
 assert.equal(G.collectionItem('title-5101'),undefined);
 const s=G.create();s.profile.title='title-5101';s.collection.unlocked.push('title-5101','title-1');
 const restored=G.migrate(JSON.parse(JSON.stringify(s)));
 assert.equal(restored.profile.title,'title-1');assert.deepEqual(restored.collection.unlocked,['title-1']);assert.ok(G.validate(restored));
 assert.throws(()=>G.equipCollection(restored,'title-5101',pool));
});
test('all bracket-prefixed songs are utage and excluded from recommendations, partners and B50',()=>{const s=ready(),u=pool.find(G.isUtage);assert.ok(u);for(const title of ['[宴]CYCLES','[協]Love You','[X]',' [星]a'])assert.ok(G.isUtage({title}));assert.ok(!G.isUtage({title:'普通歌 [Remix]'}));assert.ok(G.recommend(s,pool,100).every(c=>!G.isUtage(c)));G.preparePartner(s,pool);assert.ok(s.partnerSongs.every(x=>!G.isUtage(pool.find(c=>c.id===x.id))));G.setMode(s,'solo');G.play(s,[u,u,u],pool);assert.equal(s.records[G.key(u)].ra,0);assert.equal(s.rating,0);assert.equal(G.best(s).old.length+G.best(s).fresh.length,0);s.records[G.key(u)].ra=400;G.recalculate(s);assert.equal(s.rating,0);assert.equal(s.records[G.key(u)].ra,0);});
test('paired partner song persists; player can choose difficulty without changing partner difficulty',()=>{const s=ready(),initial=G.preparePartner(s,pool).map(x=>({...x}));const first=initial[0],other=pool.find(c=>c.id===first.id&&c.index!==first.index);assert.ok(other);G.setPartnerDifficulty(s,0,other.index,pool);assert.equal(s.partnerSongs[0].index,first.index);assert.equal(G.preparePartner(s,pool)[0].playerIndex,other.index);assert.deepEqual(s.partnerSongs.map(x=>x.id),initial.map(x=>x.id));const restored=G.migrate(JSON.parse(JSON.stringify(s)));assert.ok(G.validate(restored));const out=G.play(restored,G.recommend(restored,pool),pool),result=out.results.find(c=>c.partner&&c.id===first.id);assert.equal(result.index,other.index);assert.equal(restored.partnerSongs,null);});
test('BREAK calculator separates PERFECT 50/100, GREAT 80/60/50 and GOOD 40 base from bonus',()=>{const groups=()=>Array.from({length:5},()=>({critical:0,perfect:0,great:0,good:0,miss:0}));const expected={critical:101,perfect50:100.75,perfect100:100.5,great80:80.4,great60:60.4,great50:50.4,good:40.3,miss:0};for(const [judge,value]of Object.entries(expected)){const g=groups(),b=Object.fromEntries(Object.keys(expected).map(k=>[k,Number(k===judge)]));g[4][judge.startsWith('perfect')?'perfect':judge.startsWith('great')?'great':judge]=1;const r=G.calculateJudgements(g,b);assert.equal(r.achievement,value,judge);assert.equal(r.combo,judge==='miss'?'':judge==='good'?'FC':judge.startsWith('great')?'FC+':'AP');}const g=groups();g[0].critical=100;const r=G.calculateJudgements(g,Object.fromEntries(Object.keys(expected).map(k=>[k,0])));assert.equal(r.achievement,100);});
test('normal matching difficulty does not force FC; higher ability and familiarity reduce misses',()=>{const c=pool.find(c=>c.ds===13&&c.notes.reduce((a,b)=>a+b)>700&&!c.utage);function sample(level,practice=0){const s=G.create('student',42);s.skills={star:level,key:level,reading:level};s.liquid=600;s.practice[G.key(c)]=practice;let misses=0,clear=0;for(let i=0;i<400;i++){const r=G.simulate(s,c);misses+=r.judgements.miss;if(!r.combo)clear++;}return {misses,clear};}const normal=sample(13),expert=sample(17,30);assert.ok(normal.clear>200);assert.ok(expert.misses<normal.misses);});
test('community technique tags override note-ratio estimates and preserve SD/DX difficulty mapping',()=>{const tagged=pool.filter(c=>c.classification==='DXRating 社区标签');assert.ok(tagged.length>100);assert.ok(tagged.filter(c=>c.tags.includes('星星谱')&&!c.tags.includes('键盘谱')).every(c=>c.starWeight>=.8));assert.ok(tagged.filter(c=>c.tags.includes('键盘谱')&&!c.tags.includes('星星谱')).every(c=>c.starWeight<=.2));assert.ok(pool.find(c=>c.id==='417'&&c.index===3).tags.includes('错位'));});
test('workers and grinders play until 23:30, may return next day and continue activities',()=>{for(const job of ['worker','grinder']){const s=ready(job);s.clock=1410;assert.equal(G.availableUntil(s),1410);G.finishPlay(s);const money=s.money;G.meal(s,'hotpot');assert.equal(s.day,2);assert.equal(s.clock,33);assert.equal(s.nightActive,undefined);assert.equal(s.phase,'home');assert.equal(s.money,money-48-G.JOBS[job].daily);G.daily(s,'fun');assert.equal(s.clock,153);G.sleep(s);assert.equal(s.day,2);assert.equal(s.clock,753);assert.equal(s.drowsiness,0);assert.ok(G.validate(s));if(job==='worker'){assert.equal(s.workAbsences,1);assert.ok(s.completed.includes('shift'));}}});
test('sleeping through classes causes absences while staying awake past 04:00 is permitted',()=>{const s=G.create('student',42);s.clock=1380;G.daily(s,'fun');assert.equal(s.day,2);assert.equal(s.clock,60);G.daily(s,'fun');assert.equal(s.clock,180);G.daily(s,'wait');assert.equal(s.clock,240);G.daily(s,'wait');assert.equal(s.clock,300);assert.throws(()=>G.daily(s,'rest'),/移除/);assert.throws(()=>G.daily(s,'work'),/00:00/);G.sleep(s);assert.equal(s.clock,900);assert.equal(s.school.academic,47);assert.ok(s.absences.includes('mon-major'));assert.ok(s.absences.includes('mon-general'));assert.equal(s.drowsiness,0);assert.equal(s.stamina,100);assert.ok(G.validate(s));});
test('midnight salary/rent/daily expense are applied once; sleep after midnight does not advance an extra day',()=>{const s=G.create('worker');s.day=31;s.completed=G.schedule(s).map(c=>c.id);s.clock=1380;s.money=3000;G.daily(s,'fun');assert.equal(G.dateISO(s),'2026-04-01');assert.equal(s.money,3000-G.JOBS.worker.daily-35+6000);const before=s.money;G.sleep(s,480);assert.equal(s.day,32);assert.equal(s.money,before);const rent=G.create('grinder');rent.day=24;rent.clock=1380;G.daily(rent,'fun');assert.deepEqual(rent.paidMonths,[3]);const cash=rent.money;G.sleep(rent);assert.equal(rent.money,cash);});
test('part-time work is prohibited during and across 00:00-06:00',()=>{const s=G.create('grinder');s.clock=300;assert.throws(()=>G.daily(s,'work'),/00:00/);s.clock=1260;assert.throws(()=>G.daily(s,'work'),/00:00/);s.clock=1200;G.daily(s,'work');assert.equal(s.nightActive,undefined);assert.equal(s.clock,0);assert.throws(()=>G.daily(s,'work'),/00:00/);});
test('all achievement plates and title catalog exist; unavailable charts never give false unlocks',()=>{assert.equal(G.COLLECTIONS.filter(c=>c.category==='achievement').length,71);assert.equal(G.COLLECTIONS.filter(c=>c.kind==='title').length,1495);assert.ok(!G.COLLECTIONS.some(c=>c.kind==='title'&&/覚醒|覺醒|觉醒/.test(c.description)));const s=G.create(),item=G.COLLECTIONS.find(c=>c.id==='白将');assert.ok(item);assert.ok(!G.collectionProgress(s,item,pool).unlocked);const title=G.COLLECTIONS.find(c=>/レーティング15000達成/.test(c.description));s.rating=15000;assert.ok(G.collectionProgress(s,title,pool).unlocked);G.equipCollection(s,title.id,pool);assert.equal(s.profile.title,title.id);});
test('stamp target persists, once per calendar day; region unlock advances per PC',()=>{const s=ready(),stamp=G.COLLECTIONS.find(c=>c.category==='stamp'),region=G.COLLECTIONS.find(c=>c.kind==='plate'&&c.category==='region');G.collectionTarget(s,stamp.id);G.setMode(s,'solo');for(let day=1;day<=Math.ceil(stamp.stampTarget/2);day++){s.day=day;s.clock=600;s.people=18;s.drowsiness=0;s.queueUntil=0;s.stamina=100;s.gloves.durability=100;G.play(s,G.recommend(s,pool),pool);assert.equal(s.collection.stamps[stamp.id],Math.min(day*2,stamp.stampTarget));assert.equal(G.collectionProgress(s,stamp,pool).unlocked,day*2>=stamp.stampTarget);const saved=G.migrate(JSON.parse(JSON.stringify(s)));saved.queueUntil=0;saved.people=18;G.migrate(saved);G.play(saved,G.recommend(saved,pool),pool);assert.equal(saved.collection.stamps[stamp.id],Math.min(day*2,stamp.stampTarget));}assert.ok(G.collectionProgress(s,stamp,pool).unlocked);G.equipCollection(s,stamp.id,pool);assert.equal(s.profile.plate,stamp.id);const r=ready();G.collectionTarget(r,region.id);require('../collection').route(r);assert.equal(r.collection.regions[region.region],1);r.collection.regions[region.region]=10;G.equipCollection(r,region.id,pool);assert.ok(G.validate(G.migrate(JSON.parse(JSON.stringify(r)))));});
test('midnight ending stops action rewards and preserves terminal state',()=>{for(const action of ['fun','study','wait']){const s=G.create(action==='fun'?'worker':'student',42);s.clock=1435;s.money=G.JOBS[s.job].daily;const mood=s.mood,academic=s.school.academic;G.daily(s,action);assert.equal(s.ending,'broke');assert.equal(s.phase,'ending');assert.equal(s.mood,mood);assert.equal(s.school.academic,academic);}const s=G.create('grinder');s.clock=1438;s.money=G.JOBS.grinder.daily;G.chatSend(s,'test');assert.equal(s.ending,'broke');assert.equal(s.chatCount,0);});
test('switching to solo does not add familiarity to former partner',()=>{const s=ready();const partner=s.partner;assert.notEqual(partner,null);G.setMode(s,'solo');const before=s.npcs[partner].familiarity;G.play(s,G.recommend(s,pool),pool);assert.equal(s.npcs[partner].familiarity,before);});
test('automatic stamps require successful play and pick an unfinished reward without a target',()=>{const s=ready();assert.equal(s.collection.lastStamp,0);assert.deepEqual(s.collection.stamps,{});s.money=5;assert.throws(()=>G.play(s,G.recommend(s,pool),pool));assert.equal(s.collection.lastStamp,0);s.money=1000;G.play(s,G.recommend(s,pool),pool);const first=s.collection.stampTarget;assert.equal(s.collection.stamps[first],2);const other=G.COLLECTIONS.find(c=>c.category==='stamp'&&c.id!==first);G.collectionTarget(s,other.id);s.queueUntil=0;G.play(s,G.recommend(s,pool),pool);assert.equal(s.collection.stamps[other.id],undefined);assert.equal(s.collection.stamps[first],2);});
test('arcade kilometers count each completed leg, independent of transport, not play or reload',()=>{
 for(const mode of G.TRANSPORT)for(let arcade=0;arcade<3;arcade++){
  let s=G.create('grinder',42);G.startTrip(s);assert.equal(s.collection.distanceKm,0);G.travel(s,mode.id,arcade);
  assert.equal(s.collection.distanceKm,G.ARCADE_KM[arcade]);G.drink(s,'water');if(s.queueUntil>s.clock)G.waitQueue(s);G.play(s,G.recommend(s,pool),pool);
  assert.equal(s.collection.distanceKm,G.ARCADE_KM[arcade]);s=G.migrate(JSON.parse(JSON.stringify(s)));assert.ok(G.validate(s));
  G.finishPlay(s);G.meal(s,'home');assert.equal(s.collection.distanceKm,G.ARCADE_KM[arcade]*2);
  assert.throws(()=>G.meal(s,'home'));assert.equal(s.collection.distanceKm,G.ARCADE_KM[arcade]*2);
 }
 const s=G.create();s.money=1;G.startTrip(s);assert.throws(()=>G.travel(s,'taxi'));assert.equal(s.collection.distanceKm,0);
});
test('distance title thresholds and removed awakening titles migrate safely',()=>{
 const s=G.create(),items=G.COLLECTIONS.filter(c=>c.distanceTarget);assert.deepEqual(items.map(c=>c.distanceTarget),[100,1000,10000,100000]);
 for(const item of items){s.collection.distanceKm=item.distanceTarget-.1;assert.ok(!G.collectionProgress(s,item,pool).unlocked);s.collection.distanceKm=item.distanceTarget;G.equipCollection(s,item.id,pool);assert.equal(s.profile.title,item.id);}
 const deleted=require('../data/expansion').removedTitleIds[0];delete s.collection.distanceKm;s.profile.title=deleted;s.collection.unlocked=[deleted,'default'];s.collection.regionTarget=deleted;
 G.migrate(s);assert.equal(s.collection.distanceKm,0);assert.equal(s.profile.title,'title-1');assert.deepEqual(s.collection.unlocked,['default']);assert.equal(s.collection.regionTarget,null);assert.ok(G.validate(s));
 s.collection.distanceKm=-1;assert.ok(!G.validate(s));
});
