const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url');
const runtime=require('node:module').createRequire('C:/Users/ADMIN/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/browser-runtime.js'),{chromium}=runtime('playwright'),G=require('../engine'),vm=require('node:vm');
const music={window:{}};vm.runInNewContext(fs.readFileSync(require.resolve('../data/music.js'),'utf8'),music);const pool=G.charts(music.window.MUSIC_DATA);
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const page=await browser.newPage({viewport:{width:1234,height:960}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const version=JSON.parse(fs.readFileSync(path.resolve(__dirname,'../version.json'),'utf8')).version;
 await page.addInitScript(v=>localStorage.setItem('attendance-release',v),version);await page.addLocatorHandler(page.locator('[data-action="meal-later"]'),async()=>page.locator('[data-action="meal-later"]').click());await page.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href);
 async function load(s){s.setupDone=true;s.guide.introDone=true;await page.evaluate(s=>localStorage.setItem('attendance-simulator-v2',JSON.stringify(s)),s);await page.reload();}
 async function close(){await page.getByRole('button',{name:'关闭',exact:true}).click();}
 async function shot(name){await page.screenshot({path:path.resolve(__dirname,'../artifacts/lin-'+name+'.png'),animations:'disabled'});}
 const social=G.create('grinder',42);social.city.encounter=true;G.answerEncounter(social,0);social.day=5;social.clock=1080;social.romance.requestSeed=0;G.linTick(social);social.visits=4;social.phase='play';social.trip={rounds:1};G.finishPlay(social);social.phase='home';social.trip=null;
 for(const width of [1234,390,320]){
  await page.setViewportSize({width,height:960});await load(social);assert.equal(await page.locator('#app [data-action="relationship"]').count(),0);assert.doesNotMatch(await page.locator('#app .meal-status').innerText(),/最大体力/);
  await page.locator('[data-action="chat"]').click();await page.locator('[data-action="conversation"][data-value="小凛"]').click();assert.ok(await page.locator('.lin-request').isVisible());assert.match(await page.locator('.lin-panel').innerText(),/打到鸟（100%）/);assert.ok(await page.locator('.chat-avatar img').count());assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await shot('friend-'+width);
  await page.locator('[data-action="relationship"]').click();assert.ok(await page.locator('[data-action="love-contact"]').count());assert.match(await page.locator('.relationship-summary').innerText(),/好感 6\/100/);await close();assert.equal(await page.locator('.modal').getAttribute('data-modal'),'chat');
  await page.locator('[data-action="lin-story"]').click();await page.locator('[data-action="answer"][data-value="1"]').click();assert.equal(await page.locator('.modal').getAttribute('data-modal'),'chat');assert.match(await page.locator('.relationship-summary').innerText(),/故事 2 \/ 8/);await close();
  await page.getByRole('button',{name:'B50',exact:true}).click();assert.equal(await page.locator('.game-version').innerText(),'出勤模拟器 · '+version);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await shot('version-'+width);
 }
 const together=G.create('grinder',42);together.city.encounter=true;G.answerEncounter(together,0);together.day=2;together.clock=1080;together.money=10000;const arcade=G.linArcade(together);G.startTrip(together);G.travel(together,'taxi',arcade);G.drink(together,'water');await page.setViewportSize({width:829,height:960});await load(together);await page.locator('[data-action="attend"]').click();assert.ok(await page.locator('.lin-at-arcade').isVisible());await page.locator('.lin-at-arcade [data-action="lin-pair"]').click();assert.match(await page.locator('.partner-line').innerText(),/小凛/);const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('attendance-simulator-v2')));assert.ok(saved.partnerSongs.every(song=>pool.find(c=>c.id===song.id&&c.index===song.index).genre==='niconico & VOCALOID'));await shot('pair');assert.deepEqual(errors,[]);
 console.log('PASS: Lin private friend, task deadline, story from home, slower affection, Vocaloid partner, removed stamina label, and B50 build version at desktop/390/320 widths.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
