const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{pathToFileURL}=require('node:url');
const runtime=require('node:module').createRequire('C:/Users/ADMIN/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/browser-runtime.js'),{chromium}=runtime('playwright'),G=require('../engine');
const ctx={window:{}};vm.runInNewContext(fs.readFileSync(require.resolve('../data/music.js'),'utf8'),ctx);const pool=G.charts(ctx.window.MUSIC_DATA);
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const page=await browser.newPage({viewport:{width:1234,height:960}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{const NativeAudio=window.Audio;window.__sukunaPlayers=[];window.Audio=function(src){const audio=new NativeAudio(src);window.__sukunaPlayers.push(audio);return audio;};});await page.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href);
 async function load(s){s.setupDone=true;s.guide.introDone=true;s.nutrition.dismissed=[0];assert.ok(G.validate(s));await page.evaluate(value=>localStorage.setItem('attendance-simulator-v2',JSON.stringify(value)),s);await page.reload();}
 const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('attendance-simulator-v2')));
 async function shot(name){assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok(await page.locator('.modal').evaluate(e=>e.scrollWidth<=e.clientWidth+1));await page.screenshot({path:path.resolve(__dirname,'../artifacts/major-'+name+'.png'),animations:'disabled'});}
 const intro=G.create('grinder',42);intro.money=10000;intro.rating=16000;G.check(intro);await load(intro);await page.locator('[data-action="continue-ending"]').click();assert.match(await page.locator('.modal').innerText(),/两面宿傩/);assert.match(await page.locator('.modal').innerText(),/有意思，这是你的领域内部吗？就让我来击败你。/);
 assert.match(await page.locator('[data-action="duel-accept"]').innerText(),/最强的战绩，铭刻于机厅之巅！/);
 assert.doesNotMatch(await page.locator('.modal').innerText(),/双方游玩相同四张谱面|本场不收 PC|你才是来挑战我的人/);
 assert.equal(await page.locator('.modal.wide').count(),0);
 await page.locator('.sukuna-intro img').evaluate(img=>img.decode());
 const introTrack=(await saved()).major.duel.music;assert.ok(['yuai','aizo'].includes(introTrack));
 for(const width of [1234,390,320]){await page.setViewportSize({width,height:960});await shot('sukuna-intro-'+width);}
 await page.setViewportSize({width:1234,height:960});
 await page.locator('#duel-technique').fill('节拍·解');await page.locator('#duel-domain').fill('无尽星轨');await page.reload();assert.equal(await page.locator('#duel-domain').inputValue(),'无尽星轨');assert.doesNotMatch(await page.locator('.modal-heading').innerText(),/Rating/);
 await page.locator('[data-action="duel-accept"]').click();assert.equal(await page.locator('[data-action="picker"]').count(),2);assert.equal((await saved()).major.duel.music,introTrack);assert.equal(await page.evaluate(()=>window.__sukunaPlayers.length),1);assert.match(await page.locator('.modal').innerText(),/PANDORA PARADOXXX/);assert.match(await page.locator('.modal').innerText(),/系ぎて/);
 await page.locator('[data-action="picker"]').first().click();await page.locator('[data-action="pick"]').first().click();assert.equal(await page.locator('[data-action="duel-start"]').count(),1);await page.reload();assert.equal(await page.locator('[data-action="duel-start"]').count(),1);
 await page.locator('[data-action="duel-start"]').click();assert.match(await page.locator('.curse-scene').innerText(),/节拍·解/);assert.ok(await page.locator('[data-action="curse-choice"][data-value="talent"]').isDisabled());for(const width of [1234,390,320]){await page.setViewportSize({width,height:960});await shot('curse-'+width);}await page.setViewportSize({width:1234,height:960});await page.locator('[data-action="curse-choice"]').first().click();const feedback=(await saved()).major.performance.feedback;assert.match(await page.locator('.event-feedback').innerText(),/事件成功|事件失败/);await page.reload();assert.deepEqual((await saved()).major.performance.feedback,feedback);await require('./segment-browser.cjs').finishSegments(page);assert.match(await page.locator('.modal').innerText(),/半个舞萌痴/);assert.equal((await saved()).phase,'home');
 await page.locator('.sukuna-loss-art').evaluate(img=>img.decode());assert.match(await page.locator('.sukuna-scene').innerText(),/坐在机厅的椅子上/);
 assert.equal(await page.locator('.sukuna-scene h3').innerText(),`一刻也没有为${(await saved()).profile.id}的死感到哀悼，下一个赶到战场的是————`);
 for(const width of [1234,390,320]){
  await page.setViewportSize({width,height:960});const close=await page.locator('[data-action="duel-close"]').boundingBox(),music=await page.locator('[data-action="sukuna-music"]').boundingBox();assert.ok(music.x>=close.x+close.width);assert.ok(Math.abs((music.y+music.height/2)-(close.y+close.height/2))<2);assert.equal(await page.locator('[data-action="sukuna-music"]').count(),1);await shot('sukuna-loss-'+width);
 }
 await page.setViewportSize({width:1234,height:960});await page.locator('[data-action="duel-close"]').click();assert.equal((await saved()).major.duel.stage,'done');assert.ok(await page.evaluate(()=>window.__sukunaPlayers.every(a=>a.paused&&!a.getAttribute('src'))));
 await page.locator('[data-action="entertain"]').click();assert.equal(await page.locator('[data-action="duel-replay"]').count(),0);
 const wins=G.create('grinder',42);wins.money=10000;wins.skills={star:22,key:22,reading:22};wins.precision.base=95;wins.condition=4;for(const c of pool)wins.practice[G.key(c)]=100;wins.rating=16000;G.check(wins);G.continueGame(wins);G.acceptDuel(wins);G.startPerformance(wins,pool.filter(c=>c.ds===13).slice(0,2),0,true);while(wins.major.performance){if(wins.major.performance.feedback)G.acknowledgePerformance(wins);else if(G.currentCurse(wins))G.chooseCurse(wins,'combine');else G.chooseSegment(wins,'technique');}assert.equal(wins.major.duel.stage,'win');
 for(const width of [1234,390,320]){await page.setViewportSize({width,height:960});await load(wins);assert.match(await page.locator('.sukuna-scene').innerText(),/宿傩被你的咒术与舞萌技术打回了原来的世界里/);assert.match(await page.locator('.sukuna-scene').innerText(),/参透了咒力的核心，获得全底力加成/);assert.equal(await page.locator('[data-action="duel-close"]').count(),3);await page.locator('.sukuna-win-art').evaluate(img=>img.decode());await shot('sukuna-win-'+width);}assert.equal(await page.locator('[data-action="duel-replay"]').count(),0);await page.locator('[data-action="duel-close"]').nth(1).click();assert.equal((await saved()).major.duel.quote,1);
 const ready=G.create('grinder',42);ready.money=10000;ready.clock=900;G.startTrip(ready);G.travel(ready,'bike',0);G.drink(ready,'water');if(ready.queueUntil>ready.clock)G.waitQueue(ready);const c=pool.find(c=>c.ds<14&&c.tags.includes('拆弹'));let pending;
 for(let i=1;i<100;i++){const s=structuredClone(ready);s.seed=i*12345;G.startPerformance(s,[c,c,c]);if(G.currentSegment(s)?.segmentCount>=2){pending=s;break;}}
 await load(pending);assert.equal(await page.locator('[data-action="segment-choice"]').count(),4);await shot('segment-mobile');const firstSegment=G.currentSegment(pending);assert.match(await page.locator('.segment-progress').innerText(),/本曲难点 1/);await page.locator('[data-action="segment-choice"]').first().click();assert.ok(await page.locator('.event-feedback').isVisible());await page.locator('[data-action="performance-next"]').click();const nextSegment=G.currentSegment(await saved());assert.equal(nextSegment.index,firstSegment.index);assert.equal(nextSegment.segmentIndex,1);await page.reload();assert.match(await page.locator('.segment-progress').innerText(),/本曲难点 2/);assert.equal(await page.locator('[data-action="segment-choice"]').count(),4);await require('./segment-browser.cjs').finishSegments(page);assert.equal((await saved()).credits,pending.credits+1);
 const bird=G.create('grinder',42);bird.world.locations=['yuexiu'];bird.world.quests['电压'].stage=1;
 await load(bird);await page.locator('[data-action="entertain"]').click();await page.locator('[data-action="bird-menu"]').click();await page.locator('[data-action="bird-start"][data-value="yuexiu"]').click();assert.ok(await page.locator('#bird-hold').isVisible());const before=await saved();await page.keyboard.down(' ');await page.waitForTimeout(500);await page.keyboard.up(' ');assert.ok((await saved()).major.bird.position<before.major.bird.position);await shot('bird-mobile');await page.reload();assert.ok(await page.locator('#bird-hold').isVisible());assert.equal((await saved()).clock,before.clock);await page.locator('[data-action="bird-abandon"]').click();assert.equal((await saved()).world.entries.length,0);assert.match(await page.locator('.modal').innerText(),/鸟儿飞远/);
 assert.deepEqual(errors,[]);console.log('PASS: W6 continuation, Sukuna selection/reload/win/loss, segment settlement, bird controls/reload and desktop/390/320 layouts.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
