const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url');
const runtime=require('node:module').createRequire('C:/Users/ADMIN/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/browser-runtime.js'),{chromium}=runtime('playwright'),G=require('../engine');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href);await page.locator('input[name="talent"]').first().check();await page.getByRole('button',{name:'开始春季生活'}).click();await page.locator('[data-action="intro-skip"]').click();
 const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('attendance-simulator-v2')));
 const close=()=>page.getByRole('button',{name:'关闭',exact:true}).click();
 async function dismissMeal(){if(await page.locator('[data-action="meal-later"]').count())await page.locator('[data-action="meal-later"]').click();}
 async function load(s){await dismissMeal();s.setupDone=true;s.guide.introDone=true;const f=path.resolve(__dirname,'../artifacts/needs-fixture.json');fs.writeFileSync(f,JSON.stringify(s));await page.getByRole('button',{name:'存档与设置'}).click();await page.locator('#import-save').setInputFiles(f);await page.waitForSelector('#import-save',{state:'detached'});}
 async function shot(name){await page.locator('#toast').evaluate(e=>e.classList.remove('show'));await page.screenshot({path:path.resolve(__dirname,'../artifacts/needs-'+name+'.png'),animations:'disabled'});}
 assert.match(await page.locator('#modal-title').innerText(),/早餐/);assert.ok(await page.locator('[data-action="eat-home"][data-value="delivery"]').isVisible());await shot('breakfast-mobile');await page.locator('[data-action="eat-home"][data-value="home"]').click();assert.equal((await saved()).nutrition.meals[0],true);
 await page.locator('[data-action="attend"]').click();await page.locator('[data-action="travel"][data-value="bike"]').click();assert.equal(await page.locator('[data-action="pack-drink"]').count(),4);assert.equal(await page.locator('[data-action="pack-drink"][data-value="pink"]').count(),0);
 await page.locator('[data-action="pack-drink"][data-value="water"]').click();await page.locator('[data-action="pack-drink"][data-value="water"]').click();assert.ok(await page.locator('[data-action="pack-drink"][data-value="water"]').isDisabled());await page.locator('[data-action="pack-drink"][data-value="coffee"]').click();assert.ok((await saved()).bottles.length===3);assert.equal((await saved()).liquid,2200);await page.locator('[data-action="use-bottle"][data-value="2"]').click();assert.equal((await saved()).drink,'coffee');
 for(const width of [320,390,1123]){await page.setViewportSize({width,height:960});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok(await page.locator('.modal').evaluate(e=>e.scrollWidth<=e.clientWidth+1));await shot('drinks-'+width);}
 await page.locator('[data-action="drinks-ready"]').click();assert.equal((await saved()).phase,'play');await page.locator('[data-action="finish"]').click();assert.match(await page.locator('[data-action="meal-destination"][data-value="home"]').innerText(),/回宿舍/);assert.ok(await page.locator('[data-action="meal"][data-value="saizeriya"]').isVisible());assert.match(await page.locator('[data-action="meal"][data-value="burger"]').innerText(),/KFC.*50/s);await page.locator('[data-action="meal"][data-value="home"]').click();await dismissMeal();
 const worker=G.create('worker',42);worker.day=2;worker.nutrition.meals[0]=true;await load(worker);await page.locator('[data-action="class"]').first().click();assert.match(await page.locator('#modal-title').innerText(),/午餐/);assert.equal((await saved()).clock,720);await page.locator('[data-action="eat-home"][data-value="home"]').click();await page.locator('[data-action="class"]').first().click();assert.equal((await saved()).clock,1080);assert.match(await page.locator('#modal-title').innerText(),/晚餐/);await shot('dinner-worker');await dismissMeal();
 const thursday=G.create('student',42);thursday.day=5;thursday.clock=720;thursday.completed=G.schedule(thursday).map(c=>c.id);thursday.love=1;await load(thursday);assert.match(await page.locator('[data-action="eat-home"][data-value="burger"]').innerText(),/29.9/);await page.locator('[data-action="eat-home"][data-value="burger"]').click();assert.equal((await saved()).money,1770.1);await page.reload();assert.equal((await saved()).nutrition.meals[1],true);
 const chatter=G.create('grinder',42);chatter.clock=718;chatter.nutrition.meals[0]=true;await load(chatter);await page.locator('[data-action="chat"]').click();await page.locator('#chat-message').fill('中午好');await page.getByRole('button',{name:'发送消息',exact:true}).click();assert.match(await page.locator('#modal-title').innerText(),/午餐/);await page.locator('[data-action="eat-home"][data-value="home"]').click();assert.ok(await page.locator('#chat-message').isVisible());await close();
 const sleepy=G.create('grinder',42);sleepy.drowsiness=99.95;sleepy.nutrition.meals[0]=true;await load(sleepy);await page.locator('[data-action="daily"][data-value="work"]').click();assert.equal((await saved()).forcedSleeps,1);assert.equal((await saved()).workCount,0);await dismissMeal();assert.match(await page.locator('.drowsiness-strip').innerText(),/困意 0\/100/);
 const ended=G.create();ended.ending='ordinary';ended.phase='ending';await load(ended);await page.locator('[data-action="restart"]').click();await page.locator('[data-action="confirm-restart"]').click();assert.ok(await page.locator('#setup-form').isVisible());assert.deepEqual(errors,[]);console.log('PASS: meal reminders, lunch break, dorm labels, bottle limits/volumes, discounts, 320–1123 layouts, interrupted action, persistence and restart.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
