const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url');
const runtime=require('node:module').createRequire('C:/Users/ADMIN/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/browser-runtime.js'),{chromium}=runtime('playwright'),G=require('../engine');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addLocatorHandler(page.locator('[data-action="meal-later"]'),async()=>{await page.locator('[data-action="meal-later"]').click();});
 await page.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href);
 async function shot(name){await page.locator('#toast').evaluate(el=>el.classList.remove('show'));await page.screenshot({path:path.resolve(__dirname,'../artifacts/new-'+name+'.png'),animations:'disabled'});}
 async function close(){await page.getByRole('button',{name:'关闭',exact:true}).click();}
 async function load(s){s.setupDone=true;const file=path.resolve(__dirname,'../artifacts/round-guide-fixture.json');fs.writeFileSync(file,JSON.stringify(s));await page.getByRole('button',{name:'存档与设置'}).click();await page.locator('#import-save').setInputFiles(file);await page.waitForSelector('#import-save',{state:'detached'});}
 const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('attendance-simulator-v2')));
 assert.ok(await page.locator('[name="play-style"][value="outer"]').isChecked());await page.locator('[name="play-style"][value="inner"]').check();await page.locator('input[name="talent"]').first().check();await page.getByRole('button',{name:'开始春季生活'}).click();
 assert.equal((await saved()).playStyle,'inner');assert.equal(await page.locator('#modal-title').innerText(),'舞萌出勤群');assert.equal(await page.locator('.intro-chat').count(),0);assert.match(await page.locator('.chat-window').innerText(),/逃遁/);assert.match(await page.locator('.chat-window').innerText(),/鲁米诺/);assert.match(await page.locator('.chat-window').innerText(),/世界就会毁灭/);await shot('intro');await page.locator('[data-action="intro-next"]').click();await page.reload();assert.match(await page.locator('.chat-window').innerText(),/122 天/);await page.locator('[data-action="intro-next"]').click();await page.locator('[data-action="intro-next"]').click();assert.equal((await saved()).guide.introDone,true);const opening=(await saved()).chat;assert.equal(opening.filter(m=>m.intro).length,13);await page.locator('[data-action="chat"]').click();assert.match(await page.locator('.chat-window').innerText(),/世界就会毁灭/);assert.ok(await page.locator('#chat-message').isVisible());await close();
 await page.locator('[data-action="guide"]').click();assert.equal(await page.locator('.goal-list article').count(),10);await shot('goals');const history=(await saved()).chat;await page.locator('[data-action="intro-replay"]').click();assert.equal(await page.locator('#modal-title').innerText(),'舞萌出勤群');await page.locator('[data-action="intro-next"]').click();await page.locator('[data-action="intro-skip"]').click();assert.deepEqual((await saved()).chat,history);
 await page.getByRole('button',{name:'自定义头像'}).click();const ids=[];for(let p=0;p<4;p++){ids.push(...await page.locator('.avatar-choice').evaluateAll(els=>els.map(el=>el.dataset.value)));if(p<3)await page.locator('[data-action="avatar-page"][data-value="1"]').click();}assert.equal(new Set(ids).size,96);await shot('avatars-page4');await page.locator('.avatar-choice').last().click();const avatar=await page.locator('.avatar-choice[aria-pressed="true"] img').getAttribute('src');await close();assert.equal(await page.locator('.player-avatar img').getAttribute('src'),avatar);
 const s=G.create('grinder',42);s.people=18;s.skills={star:18,key:18,reading:18};G.startTrip(s);G.setMode(s,'pair');G.travel(s,'bike',0);G.drink(s,'water');if(s.queueUntil>s.clock)G.waitQueue(s);await load(s);
 await page.locator('[data-action="attend"]').click();assert.equal(await page.locator('[data-action="ranks"]').count(),0);assert.equal(await page.locator('[data-action="repeat-song"]').count(),0);assert.equal(await page.locator('.selection-slots button').count(),2);assert.ok(await page.locator('.partner-choices').isVisible());await page.locator('.modal').evaluate(el=>el.scrollTop=el.scrollHeight);assert.ok(await page.locator('.modal').evaluate(el=>el.scrollTop>0));await page.locator('[data-action="play"]').click();assert.equal(await page.locator('.modal').evaluate(el=>el.scrollTop),0);
 assert.equal(await page.locator('.performance-results article').count(),4);assert.equal(await page.locator('.selection-slots,.partner-choices,[data-action="picker"],[data-action="reroll"]').count(),0);assert.equal(await page.locator('.trip-info').count(),0);assert.match(await page.locator('.queue-info').innerText(),/机厅 \d+ 人/);assert.ok(!(await page.locator('.queue-info').innerText()).includes('游玩'));
 assert.ok(!(await page.locator('.performance-results').innerText()).includes(' RA'));assert.equal(await page.locator('.judgement-fold[open]').count(),0);await page.waitForFunction(()=>[...document.querySelectorAll('.grade-icon img')].every(i=>i.complete&&i.naturalWidth>0));assert.ok((await page.locator('.grade-icon img').first().getAttribute('alt')).startsWith('S'));await shot('round-results-mobile');
 await page.locator('.judgement-fold summary').first().click();assert.ok(await page.locator('.judgements').first().isVisible());assert.match(await page.locator('.judgement-fold').first().innerText(),/最大连击 \d+ \/ \d+/);assert.ok(!(await page.locator('.player-nameplate').innerText()).includes('准度'));const precision=(await saved()).precision;assert.ok(precision.base>60);await page.locator('.judgement-fold summary').first().click();await page.setViewportSize({width:1232,height:960});await shot('round-results-desktop');await page.reload();assert.deepEqual((await saved()).precision,precision);await page.locator('[data-action="attend"]').click();assert.equal(await page.locator('.selection-slots').count(),0);
 if(await page.locator('[data-action="queue"].primary-btn').count())await page.locator('[data-action="queue"].primary-btn').click();else await page.locator('[data-action="next-round"]').click();assert.ok(await page.locator('.selection-slots').isVisible());assert.ok(await page.locator('.partner-choices').isVisible());assert.equal(await page.locator('.performance-results').count(),0);
 await page.locator('[data-action="mode"][data-value="solo"]').click();if(await page.locator('[data-action="queue"].primary-btn').count())await page.locator('[data-action="queue"].primary-btn').click();assert.ok(await page.locator('[data-action="ranks"]').isVisible());await close();
 const empty=G.create('grinder',42);G.startTrip(empty);G.travel(empty,'bike',0);G.drink(empty,'water');empty.people=0;empty.crowdShift=-20;empty.queueUntil=empty.clock;await load(empty);await page.locator('[data-action="attend"]').click();
 await page.setViewportSize({width:390,height:844});assert.equal(await page.locator('[data-action="repeat-song"]').count(),3);
 await page.locator('[data-action="repeat-song"][data-value="0"]').click();const repeated=(await saved()).selectedCharts;assert.equal(repeated.length,3);assert.equal(new Set(repeated).size,1);
 await page.reload();await page.locator('[data-action="attend"]').click();assert.deepEqual((await saved()).selectedCharts,repeated);
 await page.locator('[data-action="picker"][data-value="1"]').click();await page.locator('[data-action="pick"]').first().click();const changed=(await saved()).selectedCharts;assert.equal(changed[0],repeated[0]);assert.equal(changed[2],repeated[2]);
 await page.locator('[data-action="repeat-song"][data-value="0"]').click();assert.ok(await page.locator('.modal').evaluate(el=>el.scrollWidth<=el.clientWidth+1));await shot('solo-repeat-mobile');
 await page.locator('[data-action="play"]').click();const played=await saved();assert.equal(played.last.results.length,3);assert.equal(new Set(played.last.results.map(c=>c.id+':'+c.index)).size,1);assert.deepEqual(played.last.results.map(c=>c.plays),[1,2,3]);assert.equal(await page.locator('[data-action="repeat-song"]').count(),0);assert.equal(await page.locator('.selection-slots').count(),0);assert.ok(await page.locator('[data-action="next-round"]').isVisible());await page.locator('[data-action="next-round"]').click();assert.equal(await page.locator('.selection-slots button').count(),3);await close();
 const earned=G.create('grinder');earned.credits=1;await load(earned);await page.locator('[data-action="guide"]').click();await page.locator('[data-action="goal-claim"][data-value="first-pc"]').click();assert.equal((await saved()).money,1830);await page.reload();await page.locator('[data-action="guide"]').click();assert.equal(await page.locator('[data-action="goal-claim"][data-value="first-pc"]').count(),0);
 for(const width of [320,390]){await page.setViewportSize({width,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok(await page.locator('.modal').evaluate(el=>el.scrollWidth<=el.clientWidth+1));}assert.deepEqual(errors,[]);console.log('PASS: introduction, styles, goals/rewards, 96 avatars, scroll-to-result, deferred selection, persisted review, solo courses and official grade artwork.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
