const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url');
const runtime=require('node:module').createRequire('C:/Users/ADMIN/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/browser-runtime.js'),{chromium}=runtime('playwright'),G=require('../engine');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const page=await browser.newPage({viewport:{width:1123,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addLocatorHandler(page.locator('[data-action="meal-later"]'),async()=>{await page.locator('[data-action="meal-later"]').click();});
 await page.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href);await page.locator('input[name="talent"]').first().check();await page.getByRole('button',{name:'开始春季生活'}).click();await page.locator('[data-action="intro-skip"]').click();
 async function load(s){s.setupDone=true;s.guide.introDone=true;await page.evaluate(value=>localStorage.setItem('attendance-simulator-v2',JSON.stringify(value)),s);await page.reload();}
 async function shot(name){await page.screenshot({path:path.resolve(__dirname,'../artifacts/world-'+name+'.png'),animations:'disabled'});}
 const social=G.create('grinder',42);social.world.locations=['yuexiu','shamian'];social.world.entries=['bulbul','chiffon'];social.world.quests['电压'].stage=1;social.world.quests.Toqin.stage=1;social.chat.push({id:'电压',text:'今天的白头鹎照片。',worldEntry:'bulbul',day:social.day,time:social.clock});social.npcs.find(n=>n.id==='电压').familiarity=35;social.npcs.find(n=>n.id==='Toqin').familiarity=32;G.syncFriends(social);await load(social);
 await page.locator('[data-action="chat"]').click();assert.ok(await page.locator('.conversation-list').isVisible());assert.ok(await page.locator('.conversation-main').isVisible());assert.ok(await page.locator('.conversation-info').isVisible());assert.match(await page.locator('.conversation-list').innerText(),/舞萌出勤群.*电压.*Toqin/s);await shot('chat-desktop');
 assert.equal(await page.locator('.chat-message img.pixel-art').first().getAttribute('src'),'assets/world/bulbul.png');
 await page.locator('[data-action="conversation"][data-value="电压"]').click();assert.match(await page.locator('.quest-panel').innerText(),/观鸟奇遇/);await page.getByRole('textbox',{name:'私聊消息'}).fill('自己怎么观鸟？');await page.getByRole('button',{name:'发送消息'}).click();assert.ok(await page.locator('.chat-message.self').count());assert.match(await page.locator('.chat-window').innerText(),/整段游览都要在 06:00–18:00 内/);
 await page.getByRole('textbox',{name:'私聊消息'}).fill('白头鹎怎么认？');await page.getByRole('button',{name:'发送消息'}).click();assert.match(await page.locator('.chat-message:not(.self)').last().innerText(),/白头鹎：.*白色后枕/);
 for(const width of [390,320]){await page.setViewportSize({width,height:844});assert.ok(await page.locator('.chat-window').evaluate(el=>el.scrollWidth<=el.clientWidth+1));await page.locator('.chat-message').last().scrollIntoViewIfNeeded();await shot('bird-advice-'+width);}await page.setViewportSize({width:1123,height:900});
 await page.locator('[data-action="atlas"]').first().click();assert.equal(await page.locator('.atlas-entry').count(),25);assert.match(await page.locator('.atlas-entry[data-entry="owl"]').innerText(),/隐藏记录/);assert.doesNotMatch(await page.locator('.atlas-entry[data-entry="owl"]').innerText(),/领角鸮|白云山/);assert.equal(await page.locator('.atlas-entry:not(.locked)').count(),1);await page.locator('.atlas-entry:not(.locked) img').evaluate(img=>img.decode());assert.equal(await page.locator('.atlas-entry:not(.locked) img').evaluate(img=>img.naturalWidth),256);assert.equal(await page.locator('.atlas-entry:not(.locked) img').getAttribute('src'),'assets/world/birds/bulbul.png');assert.match(await page.locator('.modal').last().innerText(),/已记录 1 \/ 25/);await shot('atlas');await page.locator('[data-action="atlas-tab"][data-value="art"]').click();assert.equal(await page.locator('.atlas-entry').count(),4);assert.equal(await page.locator('.atlas-entry:not(.locked) img').getAttribute('src'),'assets/world/chiffon.png');await page.getByRole('button',{name:'关闭'}).click();await page.getByRole('button',{name:'关闭'}).click();
 await page.setViewportSize({width:390,height:844});await page.locator('[data-action="chat"]').click();assert.ok(await page.locator('.conversation-list').isVisible());assert.equal(await page.locator('.conversation-main').isVisible(),false);await page.locator('[data-action="conversation"][data-value="电压"]').click();assert.ok(await page.locator('.conversation-main').isVisible());assert.ok(await page.locator('.conversation-back').isVisible());assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await shot('chat-mobile');await page.locator('.conversation-back').click();assert.ok(await page.locator('.conversation-list').isVisible());await page.getByRole('button',{name:'关闭'}).click();
 const collection=G.create('grinder',42);collection.world.entries=G.WORLD_ENTRIES.map(e=>e.id);collection.world.quests['电压'].stage=5;collection.world.quests['电压'].rewarded=true;
 for(const width of [1123,390,320]){
  await page.setViewportSize({width,height:900});await load(collection);await page.locator('[data-action="chat"]').click();await page.locator('[data-action="atlas"]').first().click();
  assert.equal(await page.locator('.atlas-entry:not(.locked)').count(),25);assert.match(await page.locator('.modal').last().innerText(),/已记录 25 \/ 25/);
  const images=await page.locator('.atlas-entry img').evaluateAll(async imgs=>{await Promise.all(imgs.map(img=>img.decode()));return imgs.map(img=>({width:img.naturalWidth,height:img.naturalHeight,src:img.getAttribute('src')}));});
  assert.ok(images.every(img=>img.width===256&&img.height===256&&img.src.startsWith('assets/world/birds/')));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await shot('atlas-full-'+width);
  await page.locator('.atlas-entry').last().scrollIntoViewIfNeeded();await shot('atlas-bottom-'+width);
 }
 await page.setViewportSize({width:390,height:844});const den=G.create('grinder',42);den.setupDone=true;den.guide.introDone=true;den.city.denUnlocked=true;den.money=5000;den.clock=1320;G.startTrip(den);den.arcade=5;G.travel(den,'taxi',5);G.drink(den,'water');if(den.queueUntil>den.clock)G.waitQueue(den);await load(den);await page.locator('[data-action="attend"]').click();await page.locator('[data-action="mahjong"]').click();assert.ok(await page.locator('.mahjong-table').isVisible());assert.ok(await page.locator('.mahjong-hand .tile').count()>=13);await shot('mahjong');
 for(let step=0;step<160&&await page.locator('[data-action="mahjong-help"]').count();step++)await page.locator('[data-action="mahjong-help"]').click();assert.ok(await page.locator('.mahjong-table').isVisible());assert.ok(await page.locator('.mahjong-status').innerText().then(x=>x.includes('本局结束')));await page.locator('[data-action="mahjong-choice"]').last().click();if(await page.locator('[data-action="world-ack"]').count())await page.locator('[data-action="world-ack"]').click();
 const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('attendance-simulator-v2')));assert.equal(saved.world.mahjong.rounds,1);assert.equal(saved.world.quests['COLDDD'].stage,1);
 // A repeat round has no quest notice to route the player away from the result.
 await page.locator('[data-action="attend"]').click();await page.locator('[data-action="mahjong"]').click();
 for(let step=0;step<160&&await page.locator('[data-action="mahjong-help"]').count();step++)await page.locator('[data-action="mahjong-help"]').click();
 await page.getByRole('button',{name:'结束本局，回到猫窝',exact:true}).click();
 assert.equal(await page.locator('.modal').getAttribute('data-modal'),'trip');assert.equal(await page.locator('.mahjong-table').count(),0);assert.ok(await page.locator('[data-action="play"]').isVisible());
 const repeated=await page.evaluate(()=>JSON.parse(localStorage.getItem('attendance-simulator-v2')));assert.equal(repeated.world.mahjong.rounds,2);assert.equal(repeated.world.mahjong.active,null);assert.equal(repeated.world.quests.COLDDD.stage,1);assert.equal(repeated.world.notice,null);
 await shot('mahjong-return');await page.locator('[data-action="mahjong"]').click();assert.ok(await page.locator('.mahjong-node').isVisible());await page.locator('[data-action="mahjong-leave"]').click();assert.equal(await page.locator('.modal').getAttribute('data-modal'),'trip');
 await page.reload();const restored=await page.evaluate(()=>JSON.parse(localStorage.getItem('attendance-simulator-v2')));assert.equal(restored.world.mahjong.rounds,2);assert.equal(restored.world.mahjong.active,null);
 assert.doesNotMatch(await page.locator('#toast').innerText(),/undefined|Cannot read/i);assert.deepEqual(errors,[]);console.log('PASS: desktop/mobile messenger, encyclopedia, mahjong quest settlement, repeat-round return, replay and persistence.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
