const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url');
const runtime=require('node:module').createRequire('C:/Users/ADMIN/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/browser-runtime.js'),{chromium}=runtime('playwright'),G=require('../engine');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const page=await browser.newPage({viewport:{width:1123,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addLocatorHandler(page.locator('[data-action="meal-later"]'),async()=>{await page.locator('[data-action="meal-later"]').click();});
 await page.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href);await page.locator('input[name="talent"]').first().check();await page.getByRole('button',{name:'开始春季生活'}).click();await page.locator('[data-action="intro-skip"]').click();
 async function load(s){s.setupDone=true;s.guide.introDone=true;await page.evaluate(value=>localStorage.setItem('attendance-simulator-v2',JSON.stringify(value)),s);await page.reload();}
 async function shot(name){await page.screenshot({path:path.resolve(__dirname,'../artifacts/world-'+name+'.png'),animations:'disabled'});}
 const social=G.create('grinder',42);social.world.locations=['yuexiu','shamian'];social.world.entries=['bulbul','chiffon'];social.npcs.find(n=>n.id==='电压').familiarity=35;social.npcs.find(n=>n.id==='Toqin').familiarity=32;G.syncFriends(social);await load(social);
 await page.locator('[data-action="chat"]').click();assert.ok(await page.locator('.conversation-list').isVisible());assert.ok(await page.locator('.conversation-main').isVisible());assert.ok(await page.locator('.conversation-info').isVisible());assert.match(await page.locator('.conversation-list').innerText(),/舞萌出勤群.*电压.*Toqin/s);await shot('chat-desktop');
 await page.locator('[data-action="conversation"][data-value="电压"]').click();assert.match(await page.locator('.quest-panel').innerText(),/观鸟奇遇/);await page.getByRole('textbox',{name:'私聊消息'}).fill('周末一起去观鸟');await page.getByRole('button',{name:'发送消息'}).click();assert.ok(await page.locator('.chat-message.self').count());
 await page.locator('[data-action="atlas"]').first().click();assert.equal(await page.locator('.atlas-entry').count(),4);assert.equal(await page.locator('.atlas-entry:not(.locked)').count(),1);assert.equal(await page.locator('.atlas-entry:not(.locked) img').evaluate(img=>img.naturalWidth),256);await shot('atlas');await page.getByRole('button',{name:'关闭'}).click();await page.getByRole('button',{name:'关闭'}).click();
 await page.setViewportSize({width:390,height:844});await page.locator('[data-action="chat"]').click();assert.ok(await page.locator('.conversation-list').isVisible());assert.equal(await page.locator('.conversation-main').isVisible(),false);await page.locator('[data-action="conversation"][data-value="电压"]').click();assert.ok(await page.locator('.conversation-main').isVisible());assert.ok(await page.locator('.conversation-back').isVisible());assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await shot('chat-mobile');await page.locator('.conversation-back').click();assert.ok(await page.locator('.conversation-list').isVisible());await page.getByRole('button',{name:'关闭'}).click();
 const den=G.create('grinder',42);den.setupDone=true;den.guide.introDone=true;den.city.denUnlocked=true;den.money=5000;G.startTrip(den);den.arcade=5;G.travel(den,'taxi',5);G.drink(den,'water');if(den.queueUntil>den.clock)G.waitQueue(den);await load(den);await page.locator('[data-action="attend"]').click();await page.locator('[data-action="mahjong"]').click();assert.ok(await page.locator('.mahjong-table').isVisible());assert.ok(await page.locator('.mahjong-hand .tile').count()>=13);await shot('mahjong');
 for(let step=0;step<3;step++){assert.equal(await page.locator('.mahjong-node').count(),1);await page.locator('.mahjong-node [data-action="mahjong-choice"]').first().click();}assert.ok(await page.locator('.mahjong-table').isVisible());assert.ok(await page.locator('.mahjong-status').innerText().then(x=>x.includes('本局结束')));await page.locator('[data-action="mahjong-choice"]').last().click();if(await page.locator('[data-action="world-ack"]').count())await page.locator('[data-action="world-ack"]').click();
 const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('attendance-simulator-v2')));assert.equal(saved.world.mahjong.rounds,1);assert.equal(saved.world.quests['COLDDD'].stage,1);assert.doesNotMatch(await page.locator('#toast').innerText(),/undefined|Cannot read/i);assert.deepEqual(errors,[]);console.log('PASS: desktop/mobile messenger, friend DM, encyclopedia assets and a complete rules-backed mahjong round.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
