const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const dir=path.join(__dirname,'..'),ctx={window:{}};vm.runInNewContext(fs.readFileSync(path.join(dir,'data/music.js'),'utf8'),ctx);
const data=JSON.parse(fs.readFileSync(path.join(process.env.TEMP,'cn-songs.json'))),versions=data.versions.sort((a,b)=>a.version-b.version),map={};
for(const s of ctx.window.MUSIC_DATA){const base=Number(s.id)>=10000&&Number(s.id)<100000?Number(s.id)-10000:Number(s.id),match=data.songs.find(c=>c.id===base&&c.title===s.title)||data.songs.find(c=>c.title===s.title);if(!match)continue;const diffs=match.difficulties[s.type==='DX'?'dx':'standard'];const intro=diffs?.[0]?.version||match.version;const v=versions.filter(v=>v.version<=intro).at(-1);if(v)map[s.id]={version:v.title,versionCode:v.version};}
const out={source:'https://maimai.lxns.net/api/v0/maimai/song/list?notes=true',date:'2026-09-15',versions,map};
fs.writeFileSync(path.join(dir,'data/cn-versions.js'),`(function(r){const d=${JSON.stringify(out)};if(typeof module!=='undefined')module.exports=d;else r.CN_VERSIONS=d;})(globalThis);\n`);
fs.mkdirSync(path.join(dir,'assets/rating/mainland'),{recursive:true});fs.copyFileSync(path.join(process.env.TEMP,'cn-logo.webp'),path.join(dir,'assets/rating/mainland/logo.webp'));
const colors=['#dfe8ef','#4282dc','#43ad76','#e4ba39','#df6368','#9563bf','#b57c53','#b5c5d4','#dfb34e','#d9c4a9','#ca84cd'];
const logo=fs.readFileSync(path.join(dir,'assets/rating/mainland/logo.webp')).toString('base64');
colors.forEach((c,i)=>{const gradient=i===10?'<stop stop-color="#b6f4db"/><stop offset=".35" stop-color="#c5eaff"/><stop offset=".65" stop-color="#f7ccf7"/><stop offset="1" stop-color="#fff5bd"/>':`<stop stop-color="${c}"/><stop offset=".5" stop-color="#f7fbff"/><stop offset="1" stop-color="${c}"/>`;fs.writeFileSync(path.join(dir,`assets/rating/mainland/frame-${i+1}.svg`),`<svg xmlns="http://www.w3.org/2000/svg" width="660" height="128" viewBox="0 0 660 128"><defs><linearGradient id="g">${gradient}</linearGradient></defs><rect x="3" y="3" width="654" height="122" rx="26" fill="url(#g)" stroke="white" stroke-width="6"/><path d="M22 105 54 73 86 105 118 73 150 105 182 73 214 105 246 73 278 105" fill="none" stroke="${c}" opacity=".35" stroke-width="15"/><image href="data:image/webp;base64,${logo}" x="28" y="5" width="239" height="80"/><text x="146" y="110" text-anchor="middle" font-family="Arial,sans-serif" font-weight="900" font-size="35" fill="#2684b8" stroke="white" stroke-width="1">RATING</text><rect x="300" y="20" width="322" height="90" rx="19" fill="#666" stroke="#aaa" stroke-width="6"/><path d="M364 23V107M427 23V107M490 23V107M553 23V107" stroke="#484848" stroke-width="4"/></svg>`);});
console.log({matched:Object.keys(map).length,total:ctx.window.MUSIC_DATA.length});
