import {html} from 'lit';
const names=['BASIC','ADVANCED','EXPERT','MASTER'];
const cover=c=>c.id==='11879'?'assets/kaleidxscope/glitch.png':`assets/covers/${c.id}.webp`;
export function gateBlueScreen(){return html`<section class="gate-blue-screen" role="status" aria-label="7sRef 错误画面"><div><p>检测到一个错误，<br>为避免您的世界遭到损坏，7sRef.exe已经被关闭。</p><p>如果这是您第一次看到这个错误画面，<br>&lt;请&gt;重新游玩此乐曲。如果再次出现该画面，<br>请尝试下列步骤：</p><p>检查并确定所有门处于开放状态，<br>且各个世界都能正常连接7sRef。</p><p>如果问题依旧存在，7sRef将会自动销毁并重建。</p></div></section>`;}
export function gates(s,pool){const G=window.Game,u=s.unlocks;
  const a=u.active;if(a){const d=G.UNLOCK_DATA.doors.find(d=>d.id===a.door),e=G.gateCurrent(s,pool);return html`<section class="gate-run"><div class="gate-heading"><h3>${d.name} · 第 ${Math.min(3,a.round.results.length+1)} 首</h3><strong>LIFE ${a.life}/${a.maxLife}</strong></div><progress max=${a.maxLife} value=${a.life}></progress>${a.feedback?html`<div role="status"><h3>${a.feedback.title}</h3><p>${a.feedback.text}</p></div><button class="primary-btn" data-action="gate-next">${a.life===0||a.round.results.length===3?'查看认证结果':'继续'}</button>`:html`<div class="gate-song"><img src=${cover(e.chart)} alt=${e.chart.title}><div><h3>${e.chart.title}</h3><p>${names[a.index]} ${e.chart.level}</p></div></div>${e.plan?html`<h3>${window.Judgement.segments[e.plan.tag].scene}</h3><div class="option-grid">${e.options.map(o=>html`<button class="option" data-action="gate-choice" data-value=${o.id}><b>${o.name||o.label||o.id}</b><small>成功率 ${Math.round(o.chance*100)}%</small></button>`)}</div>`:html`<p>集中精神，完成这首课题。</p><button class="primary-btn" data-action="gate-next">演奏并结算本曲</button>`}`}</section>`;}
  if(u.result?.pending){const r=u.result,d=G.UNLOCK_DATA.doors.find(d=>d.id===r.door);return html`<section class="gate-result"><span class="eyebrow">KALEIDXSCOPE RESULT</span><h2>${d.name} · ${r.passed?'通关':'挑战失败'}</h2><strong>LIFE ${r.life} / ${r.maxLife}</strong>${r.results.map((c,i)=>html`<div class="gate-song"><img src=${cover(c)} alt=${c.title}><div><small>TRACK ${i+1}</small><b>${c.title}</b><p>${c.achievement.toFixed(4)}% · ${G.rank(c.achievement)}</p></div></div>`)}<p>${r.passed?(d.hidden?'7sRef 已重新连接。':`解锁 ${G.songTitle(d.song)}${d.id==='prism'?' 及终章曲目':'，获得门之碎片'}`):'LIFE 已耗尽，后续曲目未游玩。钥匙保留，可以再次挑战。'}</p><button class="primary-btn" data-action="gate-result-close">返回机厅</button></section>`;}
  return html`<p class="gate-intro">完成区域发现入口，取得钥匙后挑战。三首连续游玩，LIFE 归零即结束。</p><div class="gate-grid">${G.UNLOCK_DATA.doors.filter(d=>!d.hidden||u.discovered[d.id]).map(d=>{const r=G.gateRules(s,d.id),m=G.REGIONS.find(m=>m.name===d.region),p=m&&G.regionState(s,m),key=u.keys.includes(d.id),found=!!u.discovered[d.id],done=d.keySongs.filter(id=>u.played.includes(id)).length;return html`<article class="gate-card" style=${`--gate-color:${d.color}`}><div class="gate-heading"><h3>${d.name}</h3><b>${u.cleared.includes(d.id)?'已通关':found?'入口已发现':'入口未发现'}</b></div><div class="gate-song"><img src=${cover({id:d.song})} alt=${G.songTitle(d.song)}><b>${G.songTitle(d.song)}</b></div>${d.hidden?'':html`<p>${d.region} · ${p?.km||0}/${m?.total||120} km</p>`}<p>${key?'已取得钥匙':d.keyText}</p>${!key&&['blue','black','red'].includes(d.id)?html`<progress value=${done} max=${d.keySongs.length}></progress><small>${done}/${d.keySongs.length} 首已游玩</small>`:''}<details><summary>钥匙曲目与挑战规则</summary><p>${d.keyText}</p><ul>${d.keySongs.map(id=>html`<li>${u.played.includes(id)?'✓ ':''}${G.songTitle(id)}</li>`)}</ul><p>${d.challengePoolNote}${d.hidden?'。':'。第 3 首为门曲。'}</p></details><p>LIFE ${r.life} · 开门第 ${r.age} 天${r.next?` · 第 ${r.next} 天进一步放宽`:''}</p><label>挑战难度<select id=${`gate-diff-${d.id}`} aria-label=${`${d.name}挑战难度`}>${names.map((name,i)=>i>=r.min?html`<option value=${i} ?selected=${i===3}>${name}</option>`:'')}</select></label><p class="form-note">${G.gateReason(s,d.id,3)}</p><button class="primary-btn" data-action="gate-start" data-value=${d.id} ?disabled=${!!G.gateReason(s,d.id,3)}>进入${d.name}</button></article>`;})}</div><details class="gate-rules"><summary>本作万花筒规则</summary><p>开门后第 1 / 4 / 7 / 10 / 14 / 21 天，LIFE 为 1 / 10 / 30 / 50 / 100 / 999。第 14 天开放红谱，第 21 天开放全部普通难度。</p><p>模拟器改编：GREAT 不扣血，GOOD −1，MISS −3，无曲间回血；前两曲从系列曲池随机抽取。白门省略名牌框条件，紫门跳过旅行伙伴。棱镜塔通关解锁终章曲并接续乱码门；乱码门首曲为隐藏课题，后两曲从终章曲池抽取。首次接续不另投币，重新挑战每场一 PC。体力与手套按实际游玩曲目结算。</p></details>`;
}
export function gateNotice(s){const n=s.unlocks.notices[0];return n?html`<div class="gate-notice"><span class="eyebrow">区域探索 · KALEIDXSCOPE</span><h2>${n.title}</h2><p>${n.text}</p><button class="primary-btn" data-action="gate-notice-close">知道了</button></div>`:'';}
