import {html} from 'lit';
import {icon} from './ui.js';
const G=window.Game;
export function majorView(s,picked,musicControl=''){
 const m=s.major,d=m.duel;
 if(m.performance?.feedback){const f=m.performance.feedback;return html`<section class="major-scene event-feedback ${f.passed?'passed':'failed'}" role="status"><small>第 ${f.index+1} 首 · ${f.kind==='curse'?'术式交锋':'难点应对'}</small><h3>${f.passed?'事件成功':'事件失败'} · ${f.title}</h3><p>${f.text}</p><button class="primary-btn" data-action="performance-next">继续</button></section>`;}
 const curse=G.currentCurse(s);
 if(curse)return html`<section class="major-scene curse-scene"><small>第 ${curse.index+1} / 4 首 · ${curse.chart.title}</small><h3>${curse.title}</h3><p>${curse.text}</p><div class="strategy-options">${curse.options.map(o=>html`<button class="option" data-action="curse-choice" data-value=${o.id} ?disabled=${o.disabled}><div><b>${o.name}</b><small>${o.requirement}</small><small>参考要求 ${o.required.toFixed(2)} · 当前综合 ${o.skill.toFixed(2)}</small><small>${o.disabled?o.lock:o.effect}</small></div><strong>${Math.round(o.chance*100)}%</strong></button>`)}</div></section>`;
 if(m.performance){const e=G.currentSegment(s);return html`<div class="major-scene"><small>第 ${e.index+1} / ${e.total} 首 · ${e.chart.title}</small><p class="segment-progress">本曲难点 ${e.segmentIndex+1} / ${e.segmentCount}</p><h3>${e.scene}</h3><p>选择这段配置的应对方式。成功稳接，失败会增加 MISS，影响本首成绩。</p><div class="strategy-options">${e.options.map(o=>html`<button class="option" data-action="segment-choice" data-value=${o.id}><div><b>${o.name}</b><small>${o.requirement}</small>${o.required!==undefined?html`<small>参考要求 ${o.required.toFixed(2)} · 当前综合 ${o.skill.toFixed(2)}</small>`:''}</div><strong>${Math.round(o.chance*100)}%</strong></button>`)}</div><p class="form-note">显示当前成功率；完成本轮所有难段选择后结算。</p></div>`;}
 if(m.bird){const b=m.bird;return html`<div class="bird-game"><p>按住按钮 / 空格 / ↑：取景框上升；松开：下降。让鸟儿留在框里。</p><div class="bird-field" aria-label="观鸟取景框"><div class="bird-viewfinder" style=${`top:${b.position}%;height:${b.width}%`}></div><span class="bird-target" style=${`top:${b.target}%`} aria-label="鸟的位置">${icon('bird')}</span></div><label>观察进度 ${Math.floor(b.progress)}%<progress max="100" value=${b.progress}></progress></label><button class="primary-btn bird-hold" id="bird-hold">按住抬高望远镜</button><button class="secondary-btn" data-action="bird-abandon">收起望远镜</button><small>离开页面会暂停，回来继续观察。不要惊扰鸟儿。</small></div>`;}
 if(d.stage==='intro')return html`<div class="sukuna-intro"><div class="event-art"><img src="assets/events/sukuna.webp" alt="两面宿傩从时空裂隙中现身" width="1919" height="1076"><div class="sukuna-caption"><small>时空裂隙中的来客</small><b>两面宿傩</b></div></div><p class="event-text">W6 达成的那一瞬，机厅的灯光停在半空。空间与时间被撕裂，两面宿傩跨入机厅。</p><p class="event-text sukuna-dialogue">“有意思，这是你的领域内部吗？就让我来击败你。”</p><fieldset class="duel-names"><legend>气氛到这里了，给你的术式和领域起个名字吧：</legend><label>术式<input id="duel-technique" maxlength="20" placeholder="节奏共鸣" .value=${d.technique||''}></label><label>领域<input id="duel-domain" maxlength="20" placeholder="无界音律" .value=${d.domain||''}></label></fieldset><div class="event-choices"><button class="option" data-action="duel-accept"><b>最强的战绩，铭刻于机厅之巅！</b>${icon('arrow-right')}</button></div></div>`;
 if(d.stage==='select')return html`<div class="sukuna-scene"><h3>对手 · 两面宿傩</h3><p>选择你的两首曲目；对手固定两首 Re:MASTER。双方四曲总分定胜负。</p><div class="duel-picks">${[0,1].map(i=>html`<button class="option" data-action="picker" data-value=${i}><div><b>你的第 ${i+1} 首</b><small>${picked[i]?.title||'点击选曲'} · ${picked[i]?.level||''}</small></div><span>更换</span></button>`)}${G.sukunaCharts().map(c=>html`<div class="option"><div><b>${c.title}</b><small>对手固定选曲 · Re:MASTER ${c.level}</small></div><span>锁定</span></div>`)}</div><button class="primary-btn" data-action="duel-start" ?disabled=${picked.length!==2}>开始四曲对决</button></div>`;
 if(d.result&&['win','loss','draw'].includes(d.stage)){return html`<div class="sukuna-scene">${d.stage==='win'?html`<img class="sukuna-win-art" src="assets/events/sukuna-win.png" alt="被击败的两面宿傩" width="640" height="929">`:''}${d.stage==='loss'?html`<img class="sukuna-loss-art" src="assets/events/sukuna-loss.png" alt="空间斩后的战场" width="280" height="204">`:''}<h3>${{win:'诅咒的终点',loss:`一刻也没有为${s.profile.id}的死感到哀悼，下一个赶到战场的是————`,draw:'不分胜负'}[d.stage]}</h3><p>${{win:`四首歌的演奏结束，在机厅——不，你所创造的${d.domain||'无界音律'}内，宿傩被你的咒术与舞萌技术打回了原来的世界里，他不可思议地看着你，现在，选一句话送给宿傩吧。`,loss:'“到此为止。”空间斩四分五裂地切碎了舞萌DX和你的领域，连熔断反转的力气都没有，你飞出了机厅。睁开眼时，你发现你坐在机厅的椅子上。',draw:'总分完全相同。宿傩挑起眉：“再来。”'}[d.stage]}</p><table class="duel-scores"><thead><tr><th>曲目</th><th>你</th><th>对手</th></tr></thead><tbody>${d.result.charts.map(c=>html`<tr><td>${c.title}${c.playerLoss||c.opponentLoss?html`<small class="curse-score-note">术式影响：你 −${(c.playerLoss||0).toFixed(4)}% · 宿傩 −${(c.opponentLoss||0).toFixed(4)}%</small>`:''}</td><td>${c.ours.toFixed(4)}%</td><td>${c.theirs.toFixed(4)}%</td></tr>`)}</tbody><tfoot><tr><th>四曲总分</th><th>${d.result.ours.toFixed(4)}%</th><th>${d.result.theirs.toFixed(4)}%</th></tr></tfoot></table>${d.stage==='win'?html`<p>解锁隐藏词条「终结诅咒之人」·现在，你参透了咒力的核心，获得全底力加成。</p>${G.SUKUNA_QUOTES.map((q,i)=>html`<button class="option" data-action="duel-close" data-value=${i}>${q}</button>`)}`:d.stage==='loss'?html`<p>隐藏词条「半个舞萌痴」· 无加成</p><div class="sukuna-result-actions"><button class="primary-btn" data-action="duel-close">继续生活</button>${musicControl}</div>`:html`<button class="primary-btn" data-action="duel-accept">再战一次</button>`}</div>`;}
 return '';
}
export function birdMenu(s){return html`<p>主动寻找鸟儿，观察成功后记录。45 分钟 · 8 体力 · ¥5。首次观鸟和隐藏鸟请通过电压的好友支线触发。</p><div class="option-grid">${['yuexiu','shamian','canton','yongqing'].map(id=>{const reason=G.birdReason(s,id),place=G.OUTINGS.find(x=>x.id===id);return html`<button class="option" data-action="bird-start" data-value=${id} ?disabled=${!!reason}><div><b>${place.name}</b><small>${reason||'开始观察'}</small></div></button>`;})}</div>`;}
