import {html} from 'lit';
import {live} from 'lit/directives/live.js';
import {icon} from './ui.js';

export function regionStatus(s){
  const G=window.Game,m=G.regionSelected(s),p=m&&G.regionState(s,m);
  return html`<div class="region-status"><span>${icon('map')}区域探索 · ${m?`${m.name} · ${p.km}/${m.total} km`:'未选择区域'}${m&&!G.regionAvailable(m,s.day)?' · 等待返场':''}</span><button class="secondary-btn" data-action="regions">${icon('route')}选择区域</button><button class="secondary-btn" data-action="gates">万花筒</button></div>`;
}
export function regionResult(r){
  if(!r)return '';
  const G=window.Game;
  return html`<section class="region-settlement" aria-label="区域探索结算"><div class="region-heading"><b>${icon('route')}${r.name}</b><strong>${r.completed?'区域完成':`前进 ${r.gain} km`}</strong></div><progress value=${r.km} max=${r.total} aria-label="区域完成度"></progress><small>${r.km} / ${r.total} km${r.already?' · 已完成':` · 游玩奖励 +${r.playBonus} · 区域曲奖励 +${r.songBonus}`}</small>${r.taskPassed?html`<p class="region-success">课题曲 CLEAR，继续前进。</p>`:''}${r.blocked?html`<p>课题曲：${r.task.title} · 下一轮任意难度达到 80% 后继续${r.stock?` · 暂存 ${r.stock} km`:''}</p>`:''}${r.rewards.length?html`<p class="region-success">获得：${r.rewards.map(id=>G.collectionItem(id).name).join('、')}</p>`:''}</section>`;
}
export function regions(s,query='',selecting=false){
  const G=window.Game,cycle=G.regionCycle(s.day),selected=G.regionSelected(s),p=selected&&G.regionState(s,selected);
  const matches=m=>!query||`${m.name} ${m.rewards.map(id=>G.collectionItem(id).name).join(' ')}`.toLowerCase().includes(query.toLowerCase());
  const filtered=G.REGIONS.filter(m=>matches(m)||m.id===selected?.id),nextDay=s.day+cycle.left;
  const date=day=>G.dateISO({...s,day});
  const option=m=>html`<option value=${m.id} ?selected=${selected?.id===m.id} ?disabled=${!G.regionAvailable(m,s.day)}>${m.name}${G.regionState(s,m).km===m.total?' · 已完成':!G.regionAvailable(m,s.day)?' · 等待返场':''}</option>`;
  return html`${selecting?'':html`<div class="collection-tabs">${[['achievement','名牌'],['title','称号'],['stamp','签到装饰'],['region','区域探索']].map(([id,name])=>html`<button data-action="collection-tab" data-value=${id} class=${id==='region'?'selected':''}>${name}</button>`)}</div>`}
    <section class="region-rotation"><div><b>${icon('calendar-days')}联动第 ${cycle.batch+1} 期</b><span>${date(s.day-(s.day-1)%10)} — ${date(Math.min(G.DAYS,nextDay-1))} · 剩余 ${Math.min(cycle.left,G.DAYS-s.day+1)} 天</span></div><p>${G.regionFamilies[cycle.batch].map(f=>f.replace(/ちほー$/,'')).join(' · ')}</p>${nextDay<=G.DAYS?html`<details><summary>下期联动 · ${date(nextDay)}</summary><p>${G.regionFamilies[cycle.nextBatch].map(f=>f.replace(/ちほー$/,'')).join(' · ')}</p></details>`:''}</section>
    <div class="region-picker"><label class="search-box">${icon('search')}<input id="collection-search" .value=${live(query)} placeholder="搜索区域 / 奖励" aria-label="搜索区域"></label><label>当前探索区域<select id="region-select" aria-label="选择探索区域"><option value="" ?selected=${!selected}>请选择区域</option><optgroup label="常驻区域">${filtered.filter(m=>!m.collab).map(option)}</optgroup><optgroup label="本期联动">${filtered.filter(m=>m.collab&&G.regionAvailable(m,s.day)).map(option)}</optgroup><optgroup label="等待返场 · 进度保留">${filtered.filter(m=>m.collab&&!G.regionAvailable(m,s.day)).map(option)}</optgroup></select></label></div>
    ${selecting?html`<div class="modal-actions region-start-actions"><button class="primary-btn" data-action="region-confirm" ?disabled=${!selected||!G.regionAvailable(selected,s.day)}>${icon('check')}确认区域，开始选曲</button><button class="secondary-btn" data-action="regions">${icon('route')}查看完整进度</button><button class="secondary-btn" data-action="gates">万花筒</button>${s.mode==='solo'?html`<button class="secondary-btn" data-action="ranks">${icon('medal')}段位挑战</button>`:''}<button class="secondary-btn" data-action="finish">${icon('log-out')}下机</button></div>`:''}
    ${selected?html`<section class="region-route"><div class="region-heading"><div><small>${selected.collab?'联动区域':'常驻区域'}</small><h3>${selected.name}</h3></div><strong>${p.km} / ${selected.total} km</strong></div><progress max=${selected.total} value=${p.km} aria-label="区域完成度"></progress>${!G.regionAvailable(selected,s.day)?html`<p class="warning">本期暂未开放，已有进度与奖励保留。</p>`:p.km===selected.total?html`<p class="region-success">区域已完成 · 可以探索其他区域</p>`:html`<p>普通上机后推进 · FC / AP / 同步成绩增加移动距离</p>`}
      ${selected.task?html`<div class="region-task"><img src=${`assets/covers/${selected.task.id}.webp`} data-cover=${selected.task.id} alt=${selected.task.title}><div><b>课题曲 · ${selected.task.title}</b><span>${p.taskCleared?'已完成':p.km>=selected.task.km?'课题已出现 · 下一轮任意难度达到 80%':'在 '+selected.task.km+' km 出现 · 任意难度达到 80%'}${s.collection.exploration.stock?` · 暂存 ${s.collection.exploration.stock} km`:''}</span></div>${s.phase==='play'&&!s.roundReview&&G.regionAvailable(selected,s.day)?html`<button class="secondary-btn" data-action="region-task" data-value=${selected.task.title}>${icon('search')}查曲</button>`:''}</div>`:''}
      <div class="region-song-unlocks">${G.regionSongNodes(selected.name).map(n=>html`<span>${G.songUnlocked(s,n.id)?'✓ 已解锁':n.km+' km'} · ${G.songTitle(n.id)}</span>`)}</div>
      <ol class="region-nodes">${selected.nodes.map(n=>{const item=G.collectionItem(n.id),earned=G.collectionProgress(s,item,[]).unlocked;return html`<li class=${earned?'earned':''}><div class="region-node-label">${icon(earned?'circle-check':'flag')}<b>${n.km} km</b></div>${item.kind==='plate'?html`<img src=${`assets/plates/${item.id}.png`} alt=${item.name}>`:html`<span class="region-title-reward">${item.name}</span>`}<span>${item.name}</span><button class="secondary-btn" data-action="equip-collection" data-value=${item.id} ?disabled=${!earned}>${s.profile[item.kind==='plate'?'plate':'title']===item.id?'已装备':earned?'装备':'未获得'}</button></li>`;})}</ol>
      <details class="region-bonus-songs"><summary>区域奖励曲 · ${selected.bonus.length} 首</summary>${selected.bonus.length?html`<p>${selected.bonus.map(id=>window.MUSIC_DATA.find(song=>song.id===id)?.title).join(' · ')}</p>`:html`<p>这个区域没有额外奖励曲。</p>`}</details></section>`:html`<p class="region-empty">选择一个区域，开始探索。</p>`}`;
}
