import {html} from 'lit';
import {icon} from './ui.js';
const G=window.Game;
function avatar(s,id,self=false){const index=G.NPC_IDS.indexOf(id),src=self?(s.profile.avatar||window.AVATARS?.[0]?.src):window.AVATARS?.[index+1]?.src;return id==='bot'&&!self?icon('bot'):src?html`<img src=${src} alt=${id+'的头像'}>`:icon('user-round');}
function entryImage(id,atlas=false){const e=G.WORLD_ENTRIES.find(e=>e.id===id);return e?html`<img class="pixel-art" src=${'assets/world/'+(atlas&&e.kind==='bird'?'birds/':'')+e.id+'.png'} alt=${e.name} width="256" height="256">`:'';}
export function questPanel(s,id){const q=G.QUESTS[id];if(!q)return '';const p=s.world.quests[id],step=q.steps[p.stage],reason=G.questReason(s,id);
 return html`<section class="quest-panel"><small>${q.title} · ${p.stage}/${q.steps.length}</small><h3>${step?.name||'故事已完成'}</h3><progress max=${q.steps.length} value=${p.stage}></progress>${step?html`<p>${step.place?G.OUTINGS.find(x=>x.id===step.place).name:'猫窝'} · ${step.time?`${step.time} 分钟 / 体力 -${step.stamina}${step.cost?' / ¥'+step.cost:''}`:'立直麻将一局 · 25 分钟 / 体力 -8'}</p>${step.night?html`<p>电压：深夜 22:00–04:00，一起进山寻找最后一位朋友吧。</p>`:''}<button class="primary-btn" data-action=${!step.time&&id==='COLDDD'?'mahjong':'quest'} data-value=${id} ?disabled=${!!reason&&reason!=='完成一局麻将以继续'}>${icon(!step.time?'grid-2x2':'footprints')}${reason||'一起出发'}</button>`:html`<b>${q.buff}</b><p>${q.effect}</p>`}</section>`;
}
export function chatApp(s,selected='group',list=false,guided=false,introContent=''){
 const id=guided?'group':selected,messages=id==='group'?s.chat:s.world.dm[id]||[],friend=s.npcs.find(n=>n.id===id);
 return html`<div class="messenger ${list&&!guided?'show-list':''}"><aside class="conversation-list"><div class="conversation-label">消息</div><button class="conversation ${id==='group'?'active':''}" data-action="conversation" data-value="group"><span class="conversation-avatar">${icon('users')}</span><span><b>舞萌出勤群</b><small>${s.chat.at(-1)?.text||'今天也一起出勤'}</small></span></button><div class="conversation-label">好友 · ${s.world.friends.length}</div>${s.world.friends.map(n=>html`<button class="conversation ${id===n?'active':''}" data-action="conversation" data-value=${n}><span class="conversation-avatar">${avatar(s,n)}</span><span><b>${n}</b><small>${s.world.dm[n]?.at(-1)?.text||'聊聊近况'}</small></span></button>`)}${!s.world.friends.length?html`<p class="friend-empty">还没有好友<br>有支线的群友眼熟度 30 后成为好友</p>`:''}<button class="conversation" data-action="atlas">${icon('book-open')}城市图鉴</button><button class="conversation" data-action="quests">${icon('notebook-pen')}好友支线</button></aside>
 <section class="conversation-main"><header class="conversation-header">${!guided?html`<button class="icon-btn conversation-back" data-action="conversation-list" aria-label="返回会话列表">${icon('chevron-left')}</button>`:''}<div><b>${id==='group'?'舞萌出勤群':id}</b><small>${id==='group'?'30 位群友':`${s.world.life[id]||'今天也在广州生活'} · 眼熟度 ${friend?.familiarity||0}`}</small></div>${!guided?html`<button class="icon-btn" data-action="atlas" aria-label="城市图鉴" title="城市图鉴">${icon('book-open')}</button>`:''}</header>
 <div class="chat-window">${messages.map((m,i)=>html`<article class="chat-message ${m.self?'self':''}"><div class="chat-avatar">${avatar(s,m.id,m.self)}</div><div><small>${m.id} · 第 ${m.day} 天 ${G.time(m.time)}</small><p>${m.self?m.text:m.text.replace(/SSS\+/g,'鸟加').replace(/SSS/g,'鸟')}</p>${m.worldEntry?entryImage(m.worldEntry):''}${m.b50?html`<button class="chat-image-button" data-action="chat-image" data-value=${i} aria-label="查看完整 B50 成绩图"><img class="chat-b50" data-b50-image=${i} alt="群聊 B50 成绩图片"></button>`:''}</div></article>`)}</div>
 ${guided?introContent:html`${id!=='group'?questPanel(s,id):''}<form id="chat-form" class="chat-compose"><input id="chat-message" maxlength="100" required aria-label=${id==='group'?'群聊消息':'私聊消息'} placeholder=${id==='group'?'在舞萌群发言':'发消息给 '+id}><button class="primary-btn" type="submit" title="发送消息" aria-label="发送消息">${icon('send')}</button></form><div class="chat-meta">${id==='group'?`发言 5 分钟 · 今日提升眼熟度 ${Math.min(s.chatDay===s.day?s.chatCount:0,5)}/5 次 · @bot查看指令`:'私聊 5 分钟 · 每日首次眼熟度 +4'}</div>`}</section>
 <aside class="conversation-info"><h3>${id==='group'?'群友动态':'好友档案'}</h3>${id==='group'?Object.entries(G.QUESTS).map(([n,q])=>html`<div class="npc-life"><b>${n}</b><p>${s.world.life[n]||'准备今天的安排'}</p><small>${q.title} · 眼熟度 ${s.npcs.find(x=>x.id===n)?.familiarity||0}/100</small></div>`):html`<p>${G.QUESTS[id]?.title||'从出勤认识的新朋友'}</p><p>${s.world.life[id]||'今天也要好好生活'}</p>`}<button class="secondary-btn" data-action="quests">${icon('notebook-pen')}好友支线</button></aside></div>`;
}
export function atlas(s,kind='bird'){
 const unlocked=s.world.quests[kind==='bird'?'电压':'Toqin'].stage>0,entries=G.WORLD_ENTRIES.filter(e=>e.kind===kind);
 return html`<div class="collection-tabs"><button data-action="atlas-tab" data-value="bird" aria-pressed=${kind==='bird'} class=${kind==='bird'?'selected':''}>广州鸟类</button><button data-action="atlas-tab" data-value="art" aria-pressed=${kind==='art'} class=${kind==='art'?'selected':''}>像素画作</button></div><p>${unlocked?`已记录 ${entries.filter(e=>s.world.entries.includes(e.id)).length} / ${entries.length}`:`完成${kind==='bird'?'电压「观鸟奇遇」':'Toqin「像素灵感漫游」'}的第一步后开启`}</p><div class="atlas-grid">${entries.map(e=>{
  const known=s.world.entries.includes(e.id),hidden=e.hidden&&!known;
  return html`<article class="atlas-entry ${known?'':'locked'}" data-entry=${e.id}>${known?entryImage(e.id,true):html`<div class="atlas-unknown">${icon(hidden?'circle-help':'lock-keyhole')}</div>`}<b>${known?e.name:hidden?'隐藏记录':'尚未记录'}</b><small>${hidden?'未知地点':G.OUTINGS.find(x=>x.id===e.place).name}</small><p>${known?e.note:hidden?'还有一位神秘的朋友，等待与你相遇。':kind==='bird'?'白天的树荫与水岸，还藏着新的身影。':'和好友一起出门，留下新的记录。'}</p></article>`;
 })}</div><p class="asset-credit">${kind==='bird'?html`鸟类像素插画由 AI 生成 · <a href="assets/world/birds/sources.json" target="_blank" rel="noreferrer">素材记录</a>`:html`像素搭档原画 © SEGA · <a href="assets/world/sources.json" target="_blank" rel="noreferrer">素材来源与许可</a>`}</p>`;
}
export function quests(s){return html`<div class="quest-list">${Object.keys(G.QUESTS).map(id=>html`<article><h3>${id}</h3><p>${s.world.life[id]||'还没开始今天的安排'}</p>${questPanel(s,id)}</article>`)}</div>`;}
export function worldNotice(s){const e=s.world.notice;return html`${e.entry?entryImage(e.entry,true):''}<p class="event-text world-event-text">${e.text}</p><button class="primary-btn" data-action="world-ack">${icon('check')}记下了</button>`;}
